// 100% Authentic Oxford & CEFR English Vocabulary Database & Course Structure
// Zero Synthetic Placeholders - Accurate IPA, Authentic Vietnamese Meanings, Real Contextual Sentences

export const COURSE_LEVELS = [
  {
    id: 'basic',
    name: 'Khóa 1: Cơ Bản (Basic - A1)',
    badge: 'Mầm Non & Lớp 1-2',
    color: 'from-cyan-500 to-blue-500 border-cyan-400 text-cyan-300',
    bgBadge: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40',
    description: 'Bảng chữ cái, Số đếm, Màu sắc, Hình dạng, Bộ phận cơ thể, Gia đình & Động vật.',
    icon: '🐣',
    targetWords: 150,
  },
  {
    id: 'elementary',
    name: 'Khóa 2: Sơ Cấp (Elementary - A2)',
    badge: 'Tiểu Học Lớp 3-5',
    color: 'from-emerald-500 to-teal-500 border-emerald-400 text-emerald-300',
    bgBadge: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
    description: 'Trường học, Đồ dùng học tập, Thức ăn, Đồ uống, Thời tiết, Mùa & Phương tiện giao thông.',
    icon: '🦁',
    targetWords: 45,
  },
  {
    id: 'intermediate',
    name: 'Khóa 3: Trung Cấp (Intermediate - B1)',
    badge: 'THCS Lớp 6-9',
    color: 'from-purple-500 to-indigo-500 border-purple-400 text-purple-300',
    bgBadge: 'bg-purple-500/20 text-purple-300 border-purple-500/40',
    description: 'Nghề nghiệp, Mua sắm, Du lịch, Thể thao, Sở thích, Nghệ thuật & Công nghệ.',
    icon: '🚀',
    targetWords: 15,
  },
  {
    id: 'advanced',
    name: 'Khóa 4: Nâng Cao (Advanced - B2/C1)',
    badge: 'THPT & Thần Đồng Ngoại Ngữ',
    color: 'from-pink-500 to-amber-500 border-pink-400 text-pink-300',
    bgBadge: 'bg-pink-500/20 text-pink-300 border-pink-500/40',
    description: 'Môi trường, Khoa học vũ trụ, Kỹ năng sống, Văn hóa quốc tế & Giao tiếp chuyên sâu.',
    icon: '👑',
    targetWords: 2,
  },
];

export const VOCAB_CATEGORIES = [
  {
    "id": "all",
    "name": "Tất Cả Chủ Đề (Chuẩn 100% Từ Điển)",
    "icon": "🌈"
  },
  {
    "id": "alphabet",
    "name": "1. Bảng Chữ Cái & Phát Âm",
    "icon": "🔤"
  },
  {
    "id": "math",
    "name": "2. Số Đếm & Toán Học",
    "icon": "🔢"
  },
  {
    "id": "colors",
    "name": "3. Màu Sắc",
    "icon": "🎨"
  },
  {
    "id": "shapes",
    "name": "4. Hình Dạng & Kích Thước",
    "icon": "📐"
  },
  {
    "id": "personal",
    "name": "5. Thông Tin Cá Nhân",
    "icon": "🪪"
  },
  {
    "id": "family",
    "name": "6. Gia Đình & Họ Hàng",
    "icon": "👨‍👩‍👧‍👦"
  },
  {
    "id": "friends",
    "name": "7. Bạn Bè & Mối Quan Hệ",
    "icon": "🤝"
  },
  {
    "id": "body",
    "name": "8. Bộ Phận Cơ Thể",
    "icon": "👁️"
  },
  {
    "id": "health",
    "name": "9. Sức Khỏe & Bệnh Tật",
    "icon": "🩺"
  },
  {
    "id": "emotions",
    "name": "10. Cảm Xúc & Tính Cách",
    "icon": "😊"
  },
  {
    "id": "daily",
    "name": "11. Hoạt Động Hằng Ngày",
    "icon": "⏰"
  },
  {
    "id": "housing",
    "name": "12. Nhà Ở & Đồ Đạc",
    "icon": "🏠"
  },
  {
    "id": "food",
    "name": "13. Đồ Ăn & Thực Phẩm",
    "icon": "🍱"
  },
  {
    "id": "drinks",
    "name": "14. Đồ Uống & Nước Giải Khát",
    "icon": "🥤"
  },
  {
    "id": "cooking",
    "name": "15. Nấu Ăn & Nhà Bếp",
    "icon": "🍳"
  },
  {
    "id": "clothes",
    "name": "16. Quần Áo & Phụ Kiện",
    "icon": "👕"
  },
  {
    "id": "school",
    "name": "17. Trường Học & Giáo Dục",
    "icon": "🏫"
  },
  {
    "id": "supplies",
    "name": "18. Đồ Dùng Học Tập",
    "icon": "🎒"
  },
  {
    "id": "subjects",
    "name": "19. Các Môn Học",
    "icon": "📚"
  },
  {
    "id": "toys",
    "name": "20. Đồ Chơi & Trò Chơi",
    "icon": "🧸"
  },
  {
    "id": "animals",
    "name": "21. Động Vật & Sinh Vật",
    "icon": "🦁"
  },
  {
    "id": "nature",
    "name": "22. Thực Vật & Thiên Nhiên",
    "icon": "🌿"
  },
  {
    "id": "weather",
    "name": "23. Thời Tiết & Khí Hậu",
    "icon": "🌤️"
  },
  {
    "id": "seasons",
    "name": "24. Mùa Trong Năm",
    "icon": "🍂"
  },
  {
    "id": "time",
    "name": "25. Thời Gian & Lịch",
    "icon": "📅"
  },
  {
    "id": "transport",
    "name": "26. Giao Thông & Phương Tiện",
    "icon": "🚗"
  },
  {
    "id": "places",
    "name": "27. Địa Điểm Thành Phố",
    "icon": "🏙️"
  },
  {
    "id": "jobs",
    "name": "28. Nghề Nghiệp",
    "icon": "👷"
  },
  {
    "id": "shopping",
    "name": "29. Mua Sắm & Tiền Bạc",
    "icon": "🛒"
  },
  {
    "id": "travel",
    "name": "30. Du Lịch & Thám Hiểm",
    "icon": "✈️"
  },
  {
    "id": "sports",
    "name": "31. Thể Thao & Vận Động",
    "icon": "⚽"
  },
  {
    "id": "hobbies",
    "name": "32. Sở Thích & Giải Trí",
    "icon": "🎨"
  },
  {
    "id": "art",
    "name": "33. Nghệ Thuật, Âm Nhạc & Phim",
    "icon": "🎬"
  },
  {
    "id": "tech",
    "name": "34. Công Nghệ & Internet",
    "icon": "💻"
  },
  {
    "id": "communication",
    "name": "35. Giao Tiếp Hằng Ngày",
    "icon": "💬"
  },
  {
    "id": "festivals",
    "name": "36. Lễ Hội & Ngày Đặc Biệt",
    "icon": "🎉"
  },
  {
    "id": "culture",
    "name": "37. Quốc Gia & Văn Hóa",
    "icon": "🌐"
  },
  {
    "id": "environment",
    "name": "38. Môi Trường & Trái Đất",
    "icon": "🌍"
  },
  {
    "id": "science",
    "name": "39. Khoa Học & Không Gian",
    "icon": "🚀"
  },
  {
    "id": "lifeskills",
    "name": "40. Kỹ Năng Sống & Xã Hội",
    "icon": "🌟"
  }
];

export const VOCABULARY_DATABASE = [
  {
    "id": "vocab-1",
    "word": "alphabet",
    "ipa": "/ˈæl.fə.bet/",
    "meaning": "bảng chữ cái",
    "category": "alphabet",
    "level": "basic",
    "image": "🔤",
    "sentence": "The English alphabet has 26 letters.",
    "sentenceVi": "Bảng chữ cái tiếng Anh có 26 chữ cái.",
    "hint": "Từ vựng từ điển chuẩn (alphabet): bảng chữ cái"
  },
  {
    "id": "vocab-2",
    "word": "letter",
    "ipa": "/ˈlet.ər/",
    "meaning": "chữ cái",
    "category": "alphabet",
    "level": "basic",
    "image": "🔤",
    "sentence": "A is the first letter of the alphabet.",
    "sentenceVi": "A là chữ cái đầu tiên trong bảng chữ cái.",
    "hint": "Từ vựng từ điển chuẩn (alphabet): chữ cái"
  },
  {
    "id": "vocab-3",
    "word": "vowel",
    "ipa": "/ˈvaʊ.əl/",
    "meaning": "nguyên âm",
    "category": "alphabet",
    "level": "basic",
    "image": "🅰️",
    "sentence": "A, E, I, O, U are the five vowels.",
    "sentenceVi": "A, E, I, O, U là năm nguyên âm.",
    "hint": "Từ vựng từ điển chuẩn (alphabet): nguyên âm"
  },
  {
    "id": "vocab-4",
    "word": "consonant",
    "ipa": "/ˈkɒn.sə.nənt/",
    "meaning": "phụ âm",
    "category": "alphabet",
    "level": "basic",
    "image": "🔤",
    "sentence": "Letters like B and C are consonants.",
    "sentenceVi": "Các chữ cái như B và C là phụ âm.",
    "hint": "Từ vựng từ điển chuẩn (alphabet): phụ âm"
  },
  {
    "id": "vocab-5",
    "word": "phonetics",
    "ipa": "/fəˈnet.ɪks/",
    "meaning": "ngữ âm học",
    "category": "alphabet",
    "level": "intermediate",
    "image": "🎙️",
    "sentence": "Phonetics helps us pronounce words correctly.",
    "sentenceVi": "Ngữ âm học giúp chúng ta phát âm từ chính xác.",
    "hint": "Từ vựng từ điển chuẩn (alphabet): ngữ âm học"
  },
  {
    "id": "vocab-6",
    "word": "pronunciation",
    "ipa": "/prəˌnʌn.siˈeɪ.ʃən/",
    "meaning": "sự phát âm",
    "category": "alphabet",
    "level": "intermediate",
    "image": "🔊",
    "sentence": "Her English pronunciation is natural.",
    "sentenceVi": "Sự phát âm tiếng Anh của cô ấy rất tự nhiên.",
    "hint": "Từ vựng từ điển chuẩn (alphabet): sự phát âm"
  },
  {
    "id": "vocab-7",
    "word": "syllable",
    "ipa": "/ˈsɪl.ə.bəl/",
    "meaning": "âm tiết",
    "category": "alphabet",
    "level": "intermediate",
    "image": "🎶",
    "sentence": "The word \"cat\" has only one syllable.",
    "sentenceVi": "Từ \"cat\" chỉ có một âm tiết.",
    "hint": "Từ vựng từ điển chuẩn (alphabet): âm tiết"
  },
  {
    "id": "vocab-8",
    "word": "intonation",
    "ipa": "/ˌɪn.təˈneɪ.ʃən/",
    "meaning": "ngữ điệu",
    "category": "alphabet",
    "level": "advanced",
    "image": "📈",
    "sentence": "Use rising intonation for yes-no questions.",
    "sentenceVi": "Dùng ngữ điệu đi lên cho câu hỏi yes-no.",
    "hint": "Từ vựng từ điển chuẩn (alphabet): ngữ điệu"
  },
  {
    "id": "vocab-9",
    "word": "spelling",
    "ipa": "/ˈspel.ɪŋ/",
    "meaning": "chính tả",
    "category": "alphabet",
    "level": "basic",
    "image": "✍️",
    "sentence": "Check your spelling in the dictionary.",
    "sentenceVi": "Kiểm tra chính tả của con trong từ điển.",
    "hint": "Từ vựng từ điển chuẩn (alphabet): chính tả"
  },
  {
    "id": "vocab-10",
    "word": "zero",
    "ipa": "/ˈzɪə.rəʊ/",
    "meaning": "số không",
    "category": "math",
    "level": "basic",
    "image": "0️⃣",
    "sentence": "Zero is the starting number on a ruler.",
    "sentenceVi": "Số không là số bắt đầu trên thước kẻ.",
    "hint": "Từ vựng từ điển chuẩn (math): số không"
  },
  {
    "id": "vocab-11",
    "word": "one",
    "ipa": "/wʌn/",
    "meaning": "số một",
    "category": "math",
    "level": "basic",
    "image": "1️⃣",
    "sentence": "Minh Anh has one cute puppy.",
    "sentenceVi": "Minh Anh có một chú chó nhỏ đáng yêu.",
    "hint": "Từ vựng từ điển chuẩn (math): số một"
  },
  {
    "id": "vocab-12",
    "word": "ten",
    "ipa": "/ten/",
    "meaning": "số mười",
    "category": "math",
    "level": "basic",
    "image": "🔟",
    "sentence": "We have ten fingers on our hands.",
    "sentenceVi": "Chúng ta có mười ngón tay trên hai bàn tay.",
    "hint": "Từ vựng từ điển chuẩn (math): số mười"
  },
  {
    "id": "vocab-13",
    "word": "hundred",
    "ipa": "/ˈhʌn.drəd/",
    "meaning": "hàng trăm",
    "category": "math",
    "level": "elementary",
    "image": "💯",
    "sentence": "Minh Anh scored one hundred points!",
    "sentenceVi": "Minh Anh đạt 100 điểm tuyệt đối!",
    "hint": "Từ vựng từ điển chuẩn (math): hàng trăm"
  },
  {
    "id": "vocab-14",
    "word": "thousand",
    "ipa": "/ˈθaʊ.zənd/",
    "meaning": "hàng nghìn",
    "category": "math",
    "level": "elementary",
    "image": "🔢",
    "sentence": "There are thousands of stars in the night sky.",
    "sentenceVi": "Có hàng nghìn ngôi sao trên bầu trời đêm.",
    "hint": "Từ vựng từ điển chuẩn (math): hàng nghìn"
  },
  {
    "id": "vocab-15",
    "word": "addition",
    "ipa": "/əˈdɪʃ.ən/",
    "meaning": "phép cộng",
    "category": "math",
    "level": "basic",
    "image": "➕",
    "sentence": "Two plus three is simple addition.",
    "sentenceVi": "Hai cộng ba là phép cộng đơn giản.",
    "hint": "Từ vựng từ điển chuẩn (math): phép cộng"
  },
  {
    "id": "vocab-16",
    "word": "subtraction",
    "ipa": "/səbˈtræk.ʃən/",
    "meaning": "phép trừ",
    "category": "math",
    "level": "basic",
    "image": "➖",
    "sentence": "Five minus two is subtraction.",
    "sentenceVi": "Năm trừ hai là phép trừ.",
    "hint": "Từ vựng từ điển chuẩn (math): phép trừ"
  },
  {
    "id": "vocab-17",
    "word": "multiplication",
    "ipa": "/ˌmʌl.tɪ.plɪˈkeɪ.ʃən/",
    "meaning": "phép nhân",
    "category": "math",
    "level": "intermediate",
    "image": "✖️",
    "sentence": "Learning multiplication tables is fun.",
    "sentenceVi": "Học bảng cửu chương nhân rất vui.",
    "hint": "Từ vựng từ điển chuẩn (math): phép nhân"
  },
  {
    "id": "vocab-18",
    "word": "division",
    "ipa": "/dɪˈvɪʒ.ən/",
    "meaning": "phép chia",
    "category": "math",
    "level": "intermediate",
    "image": "➗",
    "sentence": "Ten divided by two equals five.",
    "sentenceVi": "Mười chia cho hai bằng năm.",
    "hint": "Từ vựng từ điển chuẩn (math): phép chia"
  },
  {
    "id": "vocab-19",
    "word": "fraction",
    "ipa": "/ˈfræk.ʃən/",
    "meaning": "phân số",
    "category": "math",
    "level": "advanced",
    "image": "🍕",
    "sentence": "Half a pizza represents a fraction.",
    "sentenceVi": "Nửa cái bánh pizza tượng trưng cho phân số.",
    "hint": "Từ vựng từ điển chuẩn (math): phân số"
  },
  {
    "id": "vocab-20",
    "word": "red",
    "ipa": "/red/",
    "meaning": "màu đỏ",
    "category": "colors",
    "level": "basic",
    "image": "🔴",
    "sentence": "The apple is bright red.",
    "sentenceVi": "Quả táo có màu đỏ tươi.",
    "hint": "Từ vựng từ điển chuẩn (colors): màu đỏ"
  },
  {
    "id": "vocab-21",
    "word": "blue",
    "ipa": "/bluː/",
    "meaning": "màu xanh dương",
    "category": "colors",
    "level": "basic",
    "image": "🔵",
    "sentence": "The ocean water is clear blue.",
    "sentenceVi": "Nước biển có màu xanh dương trong trẻo.",
    "hint": "Từ vựng từ điển chuẩn (colors): màu xanh dương"
  },
  {
    "id": "vocab-22",
    "word": "yellow",
    "ipa": "/ˈjel.əʊ/",
    "meaning": "màu vàng",
    "category": "colors",
    "level": "basic",
    "image": "🟡",
    "sentence": "Sunflowers are bright yellow.",
    "sentenceVi": "Hoa hướng dương có màu vàng rực rỡ.",
    "hint": "Từ vựng từ điển chuẩn (colors): màu vàng"
  },
  {
    "id": "vocab-23",
    "word": "green",
    "ipa": "/ɡriːn/",
    "meaning": "màu xanh lá",
    "category": "colors",
    "level": "basic",
    "image": "🟢",
    "sentence": "Fresh grass is lush green.",
    "sentenceVi": "Cỏ tươi có màu xanh lá cây tốt tươi.",
    "hint": "Từ vựng từ điển chuẩn (colors): màu xanh lá"
  },
  {
    "id": "vocab-24",
    "word": "pink",
    "ipa": "/pɪŋk/",
    "meaning": "màu hồng",
    "category": "colors",
    "level": "basic",
    "image": "🌸",
    "sentence": "Minh Anh loves her pink dress.",
    "sentenceVi": "Minh Anh rất thích chiếc đầm màu hồng của mình.",
    "hint": "Từ vựng từ điển chuẩn (colors): màu hồng"
  },
  {
    "id": "vocab-25",
    "word": "purple",
    "ipa": "/ˈpɜː.pəl/",
    "meaning": "màu tím",
    "category": "colors",
    "level": "basic",
    "image": "🟣",
    "sentence": "Grapes are sweet and purple.",
    "sentenceVi": "Nho ngọt ngào và có màu tím.",
    "hint": "Từ vựng từ điển chuẩn (colors): màu tím"
  },
  {
    "id": "vocab-26",
    "word": "orange",
    "ipa": "/ˈɒr.ɪndʒ/",
    "meaning": "màu cam",
    "category": "colors",
    "level": "basic",
    "image": "🟠",
    "sentence": "The sun sets in an orange sky.",
    "sentenceVi": "Mặt trời lặn trên bầu trời màu cam.",
    "hint": "Từ vựng từ điển chuẩn (colors): màu cam"
  },
  {
    "id": "vocab-27",
    "word": "white",
    "ipa": "/waɪt/",
    "meaning": "màu trắng",
    "category": "colors",
    "level": "basic",
    "image": "⚪",
    "sentence": "Snowflakes are pure white.",
    "sentenceVi": "Bông tuyết có màu trắng tinh khôi.",
    "hint": "Từ vựng từ điển chuẩn (colors): màu trắng"
  },
  {
    "id": "vocab-28",
    "word": "black",
    "ipa": "/blæk/",
    "meaning": "màu đen",
    "category": "colors",
    "level": "basic",
    "image": "🖤",
    "sentence": "The night sky is dark black.",
    "sentenceVi": "Bầu trời đêm có màu đen thẫm.",
    "hint": "Từ vựng từ điển chuẩn (colors): màu đen"
  },
  {
    "id": "vocab-29",
    "word": "rainbow",
    "ipa": "/ˈreɪn.bəʊ/",
    "meaning": "cầu vồng",
    "category": "colors",
    "level": "elementary",
    "image": "🌈",
    "sentence": "A colorful rainbow appears after the rain.",
    "sentenceVi": "Cầu vồng rực rỡ xuất hiện sau cơn mưa.",
    "hint": "Từ vựng từ điển chuẩn (colors): cầu vồng"
  },
  {
    "id": "vocab-30",
    "word": "circle",
    "ipa": "/ˈsɜː.kəl/",
    "meaning": "hình tròn",
    "category": "shapes",
    "level": "basic",
    "image": "⭕",
    "sentence": "The full moon looks like a circle.",
    "sentenceVi": "Mặt trăng tròn trông như một hình tròn.",
    "hint": "Từ vựng từ điển chuẩn (shapes): hình tròn"
  },
  {
    "id": "vocab-31",
    "word": "square",
    "ipa": "/skweər/",
    "meaning": "hình vuông",
    "category": "shapes",
    "level": "basic",
    "image": "⏹️",
    "sentence": "A chess board is square in shape.",
    "sentenceVi": "Bàn cờ vua có hình dạng hình vuông.",
    "hint": "Từ vựng từ điển chuẩn (shapes): hình vuông"
  },
  {
    "id": "vocab-32",
    "word": "triangle",
    "ipa": "/ˈtraɪ.æŋ.ɡəl/",
    "meaning": "hình tam giác",
    "category": "shapes",
    "level": "basic",
    "image": "🔺",
    "sentence": "A slice of pizza is a triangle.",
    "sentenceVi": "Miếng bánh pizza có dạng hình tam giác.",
    "hint": "Từ vựng từ điển chuẩn (shapes): hình tam giác"
  },
  {
    "id": "vocab-33",
    "word": "rectangle",
    "ipa": "/ˈrek.tæŋ.ɡəl/",
    "meaning": "hình chữ nhật",
    "category": "shapes",
    "level": "basic",
    "image": "▭",
    "sentence": "Our classroom door is a rectangle.",
    "sentenceVi": "Cửa lớp học của chúng mình là hình chữ nhật.",
    "hint": "Từ vựng từ điển chuẩn (shapes): hình chữ nhật"
  },
  {
    "id": "vocab-34",
    "word": "star",
    "ipa": "/stɑːr/",
    "meaning": "hình ngôi sao",
    "category": "shapes",
    "level": "basic",
    "image": "⭐",
    "sentence": "A twinkling star in the sky.",
    "sentenceVi": "Một ngôi sao lấp lánh trên bầu trời.",
    "hint": "Từ vựng từ điển chuẩn (shapes): hình ngôi sao"
  },
  {
    "id": "vocab-35",
    "word": "heart",
    "ipa": "/hɑːt/",
    "meaning": "hình trái tim",
    "category": "shapes",
    "level": "basic",
    "image": "❤️",
    "sentence": "Draw a red heart for Mom.",
    "sentenceVi": "Vẽ một hình trái tim màu đỏ tặng mẹ.",
    "hint": "Từ vựng từ điển chuẩn (shapes): hình trái tim"
  },
  {
    "id": "vocab-36",
    "word": "cube",
    "ipa": "/kjuːb/",
    "meaning": "hình lập phương",
    "category": "shapes",
    "level": "elementary",
    "image": "🧊",
    "sentence": "An ice cube keeps your drink cool.",
    "sentenceVi": "Viên đá lập phương giữ nước uống mát lạnh.",
    "hint": "Từ vựng từ điển chuẩn (shapes): hình lập phương"
  },
  {
    "id": "vocab-37",
    "word": "sphere",
    "ipa": "/sfɪər/",
    "meaning": "hình cầu",
    "category": "shapes",
    "level": "intermediate",
    "image": "⚽",
    "sentence": "The Earth is a spherical planet.",
    "sentenceVi": "Trái Đất là một hành tinh có hình cầu.",
    "hint": "Từ vựng từ điển chuẩn (shapes): hình cầu"
  },
  {
    "id": "vocab-38",
    "word": "huge",
    "ipa": "/hjuːdʒ/",
    "meaning": "khổng lồ",
    "category": "shapes",
    "level": "basic",
    "image": "🐘",
    "sentence": "An elephant is a huge animal.",
    "sentenceVi": "Con voi là một động vật khổng lồ.",
    "hint": "Từ vựng từ điển chuẩn (shapes): khổng lồ"
  },
  {
    "id": "vocab-39",
    "word": "tiny",
    "ipa": "/ˈtaɪ.ni/",
    "meaning": "nhỏ bé",
    "category": "shapes",
    "level": "basic",
    "image": "🐜",
    "sentence": "An ant is a tiny insect.",
    "sentenceVi": "Con kiến là một côn trùng nhỏ bé.",
    "hint": "Từ vựng từ điển chuẩn (shapes): nhỏ bé"
  },
  {
    "id": "vocab-40",
    "word": "fullname",
    "ipa": "/ˌfʊl ˈneɪm/",
    "meaning": "họ và tên",
    "category": "personal",
    "level": "basic",
    "image": "🪪",
    "sentence": "Her full name is Nguyen Ngoc Minh Anh.",
    "sentenceVi": "Họ và tên đầy đủ của bé là Nguyễn Ngọc Minh Anh.",
    "hint": "Từ vựng từ điển chuẩn (personal): họ và tên"
  },
  {
    "id": "vocab-41",
    "word": "age",
    "ipa": "/eɪdʒ/",
    "meaning": "tuổi",
    "category": "personal",
    "level": "basic",
    "image": "🎂",
    "sentence": "Minh Anh is eight years old.",
    "sentenceVi": "Minh Anh được tám tuổi.",
    "hint": "Từ vựng từ điển chuẩn (personal): tuổi"
  },
  {
    "id": "vocab-42",
    "word": "birthday",
    "ipa": "/ˈbɜːθ.deɪ/",
    "meaning": "ngày sinh nhật",
    "category": "personal",
    "level": "basic",
    "image": "🎉",
    "sentence": "We celebrate her birthday with cake.",
    "sentenceVi": "Chúng mình tổ chức tiệc sinh nhật của bé với bánh kem.",
    "hint": "Từ vựng từ điển chuẩn (personal): ngày sinh nhật"
  },
  {
    "id": "vocab-43",
    "word": "nationality",
    "ipa": "/ˌnæʃ.ənˈæl.ə.ti/",
    "meaning": "quốc tịch",
    "category": "personal",
    "level": "elementary",
    "image": "🇻🇳",
    "sentence": "Her nationality is Vietnamese.",
    "sentenceVi": "Quốc tịch của bé là Việt Nam.",
    "hint": "Từ vựng từ điển chuẩn (personal): quốc tịch"
  },
  {
    "id": "vocab-44",
    "word": "hometown",
    "ipa": "/ˈhəʊm.taʊn/",
    "meaning": "quê hương",
    "category": "personal",
    "level": "elementary",
    "image": "🏡",
    "sentence": "Da Nang is my beautiful hometown.",
    "sentenceVi": "Đà Nẵng là quê hương tươi đẹp của tôi.",
    "hint": "Từ vựng từ điển chuẩn (personal): quê hương"
  },
  {
    "id": "vocab-45",
    "word": "address",
    "ipa": "/əˈdres/",
    "meaning": "địa chỉ",
    "category": "personal",
    "level": "basic",
    "image": "📍",
    "sentence": "Write your home address clearly.",
    "sentenceVi": "Hãy viết địa chỉ nhà của con thật rõ ràng.",
    "hint": "Từ vựng từ điển chuẩn (personal): địa chỉ"
  },
  {
    "id": "vocab-46",
    "word": "hobby",
    "ipa": "/ˈhɒb.i/",
    "meaning": "sở thích",
    "category": "personal",
    "level": "basic",
    "image": "🎨",
    "sentence": "Painting flowers is her favorite hobby.",
    "sentenceVi": "Vẽ hoa là sở thích yêu thích của bé.",
    "hint": "Từ vựng từ điển chuẩn (personal): sở thích"
  },
  {
    "id": "vocab-47",
    "word": "dream",
    "ipa": "/driːm/",
    "meaning": "ước mơ",
    "category": "personal",
    "level": "elementary",
    "image": "🌟",
    "sentence": "Follow your dreams with bravery.",
    "sentenceVi": "Hãy dũng cảm theo đuổi những ước mơ.",
    "hint": "Từ vựng từ điển chuẩn (personal): ước mơ"
  },
  {
    "id": "vocab-48",
    "word": "father",
    "ipa": "/ˈfɑː.ðər/",
    "meaning": "bố/cha",
    "category": "family",
    "level": "basic",
    "image": "👨",
    "sentence": "Father teaches me how to ride a bike.",
    "sentenceVi": "Bố dạy con cách đạp xe.",
    "hint": "Từ vựng từ điển chuẩn (family): bố/cha"
  },
  {
    "id": "vocab-49",
    "word": "mother",
    "ipa": "/ˈmʌð.ər/",
    "meaning": "mẹ",
    "category": "family",
    "level": "basic",
    "image": "👩",
    "sentence": "Mother prepares warm meals for us.",
    "sentenceVi": "Mẹ chuẩn bị những bữa ăn ấm áp cho gia đình.",
    "hint": "Từ vựng từ điển chuẩn (family): mẹ"
  },
  {
    "id": "vocab-50",
    "word": "brother",
    "ipa": "/ˈbrʌð.ər/",
    "meaning": "anh/em trai",
    "category": "family",
    "level": "basic",
    "image": "👦",
    "sentence": "My brother plays soccer with me.",
    "sentenceVi": "Anh trai cùng con chơi bóng đá.",
    "hint": "Từ vựng từ điển chuẩn (family): anh/em trai"
  },
  {
    "id": "vocab-51",
    "word": "sister",
    "ipa": "/ˈsɪs.tər/",
    "meaning": "chị/em gái",
    "category": "family",
    "level": "basic",
    "image": "👧",
    "sentence": "Sister reads stories before bedtime.",
    "sentenceVi": "Chị gái đọc truyện trước giờ đi ngủ.",
    "hint": "Từ vựng từ điển chuẩn (family): chị/em gái"
  },
  {
    "id": "vocab-52",
    "word": "grandfather",
    "ipa": "/ˈɡræn.fɑː.ðər/",
    "meaning": "ông nội/ông ngoại",
    "category": "family",
    "level": "basic",
    "image": "👴",
    "sentence": "Grandfather tells wonderful stories.",
    "sentenceVi": "Ông kể những câu chuyện tuyệt vời.",
    "hint": "Từ vựng từ điển chuẩn (family): ông nội/ông ngoại"
  },
  {
    "id": "vocab-53",
    "word": "grandmother",
    "ipa": "/ˈɡræn.mʌð.ər/",
    "meaning": "bà nội/bà ngoại",
    "category": "family",
    "level": "basic",
    "image": "👵",
    "sentence": "Grandmother bakes delicious biscuits.",
    "sentenceVi": "Bà nướng những chiếc bánh quy thơm ngon.",
    "hint": "Từ vựng từ điển chuẩn (family): bà nội/bà ngoại"
  },
  {
    "id": "vocab-54",
    "word": "uncle",
    "ipa": "/ˈʌŋ.kəl/",
    "meaning": "chú/bác/cậu",
    "category": "family",
    "level": "elementary",
    "image": "👨‍💼",
    "sentence": "Uncle visits our home on weekends.",
    "sentenceVi": "Chú đến thăm nhà vào cuối tuần.",
    "hint": "Từ vựng từ điển chuẩn (family): chú/bác/cậu"
  },
  {
    "id": "vocab-55",
    "word": "aunt",
    "ipa": "/ɑːnt/",
    "meaning": "cô/dì/thím",
    "category": "family",
    "level": "elementary",
    "image": "👩‍💼",
    "sentence": "Aunt brings sweet apples for Minh Anh.",
    "sentenceVi": "Dì mang những quả táo ngọt cho Minh Anh.",
    "hint": "Từ vựng từ điển chuẩn (family): cô/dì/thím"
  },
  {
    "id": "vocab-56",
    "word": "cousin",
    "ipa": "/ˈkʌz.ən/",
    "meaning": "anh chị em họ",
    "category": "family",
    "level": "elementary",
    "image": "🧒",
    "sentence": "We play games with our cousins.",
    "sentenceVi": "Chúng con chơi trò chơi cùng anh chị em họ.",
    "hint": "Từ vựng từ điển chuẩn (family): anh chị em họ"
  },
  {
    "id": "vocab-57",
    "word": "friend",
    "ipa": "/frend/",
    "meaning": "bạn bè",
    "category": "friends",
    "level": "basic",
    "image": "🤝",
    "sentence": "Minh Anh has many loyal friends.",
    "sentenceVi": "Minh Anh có nhiều người bạn trung thành.",
    "hint": "Từ vựng từ điển chuẩn (friends): bạn bè"
  },
  {
    "id": "vocab-58",
    "word": "bestfriend",
    "ipa": "/best frend/",
    "meaning": "bạn thân",
    "category": "friends",
    "level": "basic",
    "image": "💖",
    "sentence": "My best friend shares her toys with me.",
    "sentenceVi": "Bạn thân của con cùng chia sẻ đồ chơi.",
    "hint": "Từ vựng từ điển chuẩn (friends): bạn thân"
  },
  {
    "id": "vocab-59",
    "word": "classmate",
    "ipa": "/ˈklɑːs.meɪt/",
    "meaning": "bạn cùng lớp",
    "category": "friends",
    "level": "basic",
    "image": "🧑‍🎓",
    "sentence": "Be kind to your classmates.",
    "sentenceVi": "Hãy luôn tốt bụng với các bạn cùng lớp.",
    "hint": "Từ vựng từ điển chuẩn (friends): bạn cùng lớp"
  },
  {
    "id": "vocab-60",
    "word": "friendship",
    "ipa": "/ˈfrend.ʃɪp/",
    "meaning": "tình bạn",
    "category": "friends",
    "level": "elementary",
    "image": "👫",
    "sentence": "True friendship is valuable.",
    "sentenceVi": "Tình bạn chân thành là điều vô cùng quý giá.",
    "hint": "Từ vựng từ điển chuẩn (friends): tình bạn"
  },
  {
    "id": "vocab-61",
    "word": "sharing",
    "ipa": "/ˈʃeə.rɪŋ/",
    "meaning": "sự chia sẻ",
    "category": "friends",
    "level": "basic",
    "image": "🎁",
    "sentence": "Sharing snacks makes everyone happy.",
    "sentenceVi": "Chia sẻ đồ ăn vặt mang lại niềm vui cho mọi người.",
    "hint": "Từ vựng từ điển chuẩn (friends): sự chia sẻ"
  },
  {
    "id": "vocab-62",
    "word": "respect",
    "ipa": "/rɪˈspekt/",
    "meaning": "sự tôn trọng",
    "category": "friends",
    "level": "intermediate",
    "image": "🙏",
    "sentence": "Show respect to elders and teachers.",
    "sentenceVi": "Thể hiện sự tôn trọng với người lớn và thầy cô.",
    "hint": "Từ vựng từ điển chuẩn (friends): sự tôn trọng"
  },
  {
    "id": "vocab-63",
    "word": "head",
    "ipa": "/hed/",
    "meaning": "đầu",
    "category": "body",
    "level": "basic",
    "image": "🗣️",
    "sentence": "Nod your head when you agree.",
    "sentenceVi": "Gật đầu khi con đồng ý.",
    "hint": "Từ vựng từ điển chuẩn (body): đầu"
  },
  {
    "id": "vocab-64",
    "word": "hair",
    "ipa": "/heər/",
    "meaning": "mái tóc",
    "category": "body",
    "level": "basic",
    "image": "💇",
    "sentence": "She has long shiny black hair.",
    "sentenceVi": "Cô ấy có mái tóc đen dài bóng mượt.",
    "hint": "Từ vựng từ điển chuẩn (body): mái tóc"
  },
  {
    "id": "vocab-65",
    "word": "face",
    "ipa": "/feɪs/",
    "meaning": "khuôn mặt",
    "category": "body",
    "level": "basic",
    "image": "😊",
    "sentence": "A smiling face lights up the room.",
    "sentenceVi": "Khuôn mặt mỉm cười thắp sáng cả phòng.",
    "hint": "Từ vựng từ điển chuẩn (body): khuôn mặt"
  },
  {
    "id": "vocab-66",
    "word": "eye",
    "ipa": "/aɪ/",
    "meaning": "đôi mắt",
    "category": "body",
    "level": "basic",
    "image": "👁️",
    "sentence": "Her eyes are bright and full of joy.",
    "sentenceVi": "Đôi mắt bé sáng long lanh và đầy niềm vui.",
    "hint": "Từ vựng từ điển chuẩn (body): đôi mắt"
  },
  {
    "id": "vocab-67",
    "word": "ear",
    "ipa": "/ɪər/",
    "meaning": "lỗ tai",
    "category": "body",
    "level": "basic",
    "image": "👂",
    "sentence": "Listen carefully with both ears.",
    "sentenceVi": "Lắng nghe cẩn thận bằng cả hai tai.",
    "hint": "Từ vựng từ điển chuẩn (body): lỗ tai"
  },
  {
    "id": "vocab-68",
    "word": "nose",
    "ipa": "/nəʊz/",
    "meaning": "chiếc mũi",
    "category": "body",
    "level": "basic",
    "image": "👃",
    "sentence": "Smell the sweet rose with your nose.",
    "sentenceVi": "Ngửi bông hoa hồng thơm ngát bằng chiếc mũi.",
    "hint": "Từ vựng từ điển chuẩn (body): chiếc mũi"
  },
  {
    "id": "vocab-69",
    "word": "mouth",
    "ipa": "/maʊθ/",
    "meaning": "miệng",
    "category": "body",
    "level": "basic",
    "image": "👄",
    "sentence": "Smile brightly with your mouth.",
    "sentenceVi": "Mỉm cười rạng rỡ bằng khuôn miệng.",
    "hint": "Từ vựng từ điển chuẩn (body): miệng"
  },
  {
    "id": "vocab-70",
    "word": "tooth",
    "ipa": "/tuːθ/",
    "meaning": "chiếc răng",
    "category": "body",
    "level": "basic",
    "image": "🦷",
    "sentence": "Brush every tooth after eating.",
    "sentenceVi": "Đánh sạch từng chiếc răng sau khi ăn.",
    "hint": "Từ vựng từ điển chuẩn (body): chiếc răng"
  },
  {
    "id": "vocab-71",
    "word": "hand",
    "ipa": "/hænd/",
    "meaning": "bàn tay",
    "category": "body",
    "level": "basic",
    "image": "🤚",
    "sentence": "Wash your hands clean with soap.",
    "sentenceVi": "Rửa sạch bàn tay bằng xà phòng.",
    "hint": "Từ vựng từ điển chuẩn (body): bàn tay"
  },
  {
    "id": "vocab-72",
    "word": "healthy",
    "ipa": "/ˈhel.θi/",
    "meaning": "khỏe mạnh",
    "category": "health",
    "level": "basic",
    "image": "💪",
    "sentence": "Eating vegetables keeps you healthy.",
    "sentenceVi": "Ăn rau củ giúp con luôn khỏe mạnh.",
    "hint": "Từ vựng từ điển chuẩn (health): khỏe mạnh"
  },
  {
    "id": "vocab-73",
    "word": "cough",
    "ipa": "/kɒf/",
    "meaning": "bị ho",
    "category": "health",
    "level": "basic",
    "image": "🗣️",
    "sentence": "Cover your mouth when you cough.",
    "sentenceVi": "Che miệng lại khi con bị ho.",
    "hint": "Từ vựng từ điển chuẩn (health): bị ho"
  },
  {
    "id": "vocab-74",
    "word": "fever",
    "ipa": "/ˈfiː.vər/",
    "meaning": "bị sốt",
    "category": "health",
    "level": "elementary",
    "image": "🌡️",
    "sentence": "Drink warm water when you have a fever.",
    "sentenceVi": "Uống nước ấm khi con bị sốt.",
    "hint": "Từ vựng từ điển chuẩn (health): bị sốt"
  },
  {
    "id": "vocab-75",
    "word": "doctor",
    "ipa": "/ˈdɒk.tər/",
    "meaning": "bác sĩ",
    "category": "health",
    "level": "basic",
    "image": "🩺",
    "sentence": "The doctor checks your health.",
    "sentenceVi": "Bác sĩ kiểm tra sức khỏe cho con.",
    "hint": "Từ vựng từ điển chuẩn (health): bác sĩ"
  },
  {
    "id": "vocab-76",
    "word": "nurse",
    "ipa": "/nɜːs/",
    "meaning": "y tá",
    "category": "health",
    "level": "basic",
    "image": "🧑‍⚕️",
    "sentence": "The nurse takes good care of patients.",
    "sentenceVi": "Y tá chăm sóc bệnh nhân rất chu đáo.",
    "hint": "Từ vựng từ điển chuẩn (health): y tá"
  },
  {
    "id": "vocab-77",
    "word": "hospital",
    "ipa": "/ˈhɒs.pɪ.təl/",
    "meaning": "bệnh viện",
    "category": "health",
    "level": "elementary",
    "image": "🏥",
    "sentence": "A modern hospital provides medical care.",
    "sentenceVi": "Bệnh viện hiện đại cung cấp dịch vụ y tế.",
    "hint": "Từ vựng từ điển chuẩn (health): bệnh viện"
  },
  {
    "id": "vocab-78",
    "word": "medicine",
    "ipa": "/ˈmed.sən/",
    "meaning": "liều thuốc",
    "category": "health",
    "level": "elementary",
    "image": "💊",
    "sentence": "Take medicine as advised by the doctor.",
    "sentenceVi": "Uống thuốc theo sự chỉ dẫn của bác sĩ.",
    "hint": "Từ vựng từ điển chuẩn (health): liều thuốc"
  },
  {
    "id": "vocab-79",
    "word": "happy",
    "ipa": "/ˈhæp.i/",
    "meaning": "vui vẻ",
    "category": "emotions",
    "level": "basic",
    "image": "😊",
    "sentence": "Minh Anh feels extremely happy today.",
    "sentenceVi": "Hôm nay Minh Anh cảm thấy vô cùng vui vẻ.",
    "hint": "Từ vựng từ điển chuẩn (emotions): vui vẻ"
  },
  {
    "id": "vocab-80",
    "word": "sad",
    "ipa": "/sæd/",
    "meaning": "buồn rầu",
    "category": "emotions",
    "level": "basic",
    "image": "😢",
    "sentence": "A warm hug comforts a sad friend.",
    "sentenceVi": "Một cái ôm ấm áp an ủi người bạn đang buồn.",
    "hint": "Từ vựng từ điển chuẩn (emotions): buồn rầu"
  },
  {
    "id": "vocab-81",
    "word": "brave",
    "ipa": "/breɪv/",
    "meaning": "dũng cảm",
    "category": "emotions",
    "level": "basic",
    "image": "🦁",
    "sentence": "Be brave and try new challenges.",
    "sentenceVi": "Hãy dũng cảm và thử sức với thử thách mới.",
    "hint": "Từ vựng từ điển chuẩn (emotions): dũng cảm"
  },
  {
    "id": "vocab-82",
    "word": "kind",
    "ipa": "/kaɪnd/",
    "meaning": "tốt bụng",
    "category": "emotions",
    "level": "basic",
    "image": "💖",
    "sentence": "A kind gesture warms the heart.",
    "sentenceVi": "Cử chỉ tốt bụng làm ấm lòng mọi người.",
    "hint": "Từ vựng từ điển chuẩn (emotions): tốt bụng"
  },
  {
    "id": "vocab-83",
    "word": "honest",
    "ipa": "/ˈɒn.ɪst/",
    "meaning": "trung thực",
    "category": "emotions",
    "level": "elementary",
    "image": "🤝",
    "sentence": "Always tell the truth and be honest.",
    "sentenceVi": "Luôn nói sự thật và giữ lòng trung thực.",
    "hint": "Từ vựng từ điển chuẩn (emotions): trung thực"
  },
  {
    "id": "vocab-84",
    "word": "patient",
    "ipa": "/ˈpeɪ.ʃənt/",
    "meaning": "kiên nhẫn",
    "category": "emotions",
    "level": "intermediate",
    "image": "⏳",
    "sentence": "Be patient when solving math problems.",
    "sentenceVi": "Hãy kiên nhẫn khi giải các bài toán.",
    "hint": "Từ vựng từ điển chuẩn (emotions): kiên nhẫn"
  },
  {
    "id": "vocab-85",
    "word": "wakeup",
    "ipa": "/weɪk ʌp/",
    "meaning": "thức dậy",
    "category": "daily",
    "level": "basic",
    "image": "⏰",
    "sentence": "I wake up at six in the morning.",
    "sentenceVi": "Tôi thức dậy lúc sáu giờ sáng.",
    "hint": "Từ vựng từ điển chuẩn (daily): thức dậy"
  },
  {
    "id": "vocab-86",
    "word": "brush",
    "ipa": "/brʌʃ/",
    "meaning": "đánh răng",
    "category": "daily",
    "level": "basic",
    "image": "🪥",
    "sentence": "Brush your teeth twice daily.",
    "sentenceVi": "Đánh răng hai lần mỗi ngày.",
    "hint": "Từ vựng từ điển chuẩn (daily): đánh răng"
  },
  {
    "id": "vocab-87",
    "word": "shower",
    "ipa": "/ˈʃaʊ.ər/",
    "meaning": "tắm rửa",
    "category": "daily",
    "level": "basic",
    "image": "🚿",
    "sentence": "Take a refreshing shower after school.",
    "sentenceVi": "Tắm rửa sảng khoái sau giờ học.",
    "hint": "Từ vựng từ điển chuẩn (daily): tắm rửa"
  },
  {
    "id": "vocab-88",
    "word": "breakfast",
    "ipa": "/ˈbrek.fəst/",
    "meaning": "bữa ăn sáng",
    "category": "daily",
    "level": "basic",
    "image": "🍳",
    "sentence": "Eat a nutritious breakfast.",
    "sentenceVi": "Ăn một bữa sáng đầy đủ dinh dưỡng.",
    "hint": "Từ vựng từ điển chuẩn (daily): bữa ăn sáng"
  },
  {
    "id": "vocab-89",
    "word": "lunch",
    "ipa": "/lʌntʃ/",
    "meaning": "bữa ăn trưa",
    "category": "daily",
    "level": "basic",
    "image": "🍱",
    "sentence": "Have lunch with friends at school.",
    "sentenceVi": "Ăn trưa cùng bạn bè tại trường.",
    "hint": "Từ vựng từ điển chuẩn (daily): bữa ăn trưa"
  },
  {
    "id": "vocab-90",
    "word": "dinner",
    "ipa": "/ˈdɪn.ər/",
    "meaning": "bữa ăn tối",
    "category": "daily",
    "level": "basic",
    "image": "🍲",
    "sentence": "Family gathers together for dinner.",
    "sentenceVi": "Gia đình quây quần bên nhau ăn tối.",
    "hint": "Từ vựng từ điển chuẩn (daily): bữa ăn tối"
  },
  {
    "id": "vocab-91",
    "word": "house",
    "ipa": "/haʊs/",
    "meaning": "ngôi nhà",
    "category": "housing",
    "level": "basic",
    "image": "🏠",
    "sentence": "Our house is full of laughter.",
    "sentenceVi": "Ngôi nhà của chúng mình ngập tràn tiếng cười.",
    "hint": "Từ vựng từ điển chuẩn (housing): ngôi nhà"
  },
  {
    "id": "vocab-92",
    "word": "livingroom",
    "ipa": "/ˈlɪv.ɪŋ ˌruːm/",
    "meaning": "phòng khách",
    "category": "housing",
    "level": "basic",
    "image": "🛋️",
    "sentence": "We sit on the sofa in the living room.",
    "sentenceVi": "Chúng mình ngồi trên ghế sofa ở phòng khách.",
    "hint": "Từ vựng từ điển chuẩn (housing): phòng khách"
  },
  {
    "id": "vocab-93",
    "word": "bedroom",
    "ipa": "/ˈbed.ruːm/",
    "meaning": "phòng ngủ",
    "category": "housing",
    "level": "basic",
    "image": "🛏️",
    "sentence": "Her bedroom is quiet and comfortable.",
    "sentenceVi": "Phòng ngủ của bé rất yên tĩnh và thoải mái.",
    "hint": "Từ vựng từ điển chuẩn (housing): phòng ngủ"
  },
  {
    "id": "vocab-94",
    "word": "kitchen",
    "ipa": "/ˈkɪtʃ.ən/",
    "meaning": "phòng bếp",
    "category": "housing",
    "level": "basic",
    "image": "🍳",
    "sentence": "Mom cooks delicious soup in the kitchen.",
    "sentenceVi": "Mẹ nấu súp thơm ngon trong phòng bếp.",
    "hint": "Từ vựng từ điển chuẩn (housing): phòng bếp"
  },
  {
    "id": "vocab-95",
    "word": "bathroom",
    "ipa": "/ˈbɑːθ.ruːm/",
    "meaning": "phòng tắm",
    "category": "housing",
    "level": "basic",
    "image": "🛁",
    "sentence": "Keep the bathroom clean and dry.",
    "sentenceVi": "Giữ phòng tắm luôn sạch sẽ và khô ráo.",
    "hint": "Từ vựng từ điển chuẩn (housing): phòng tắm"
  },
  {
    "id": "vocab-96",
    "word": "garden",
    "ipa": "/ˈɡɑː.dən/",
    "meaning": "sân vườn",
    "category": "housing",
    "level": "elementary",
    "image": "🏡",
    "sentence": "Red roses grow nicely in our garden.",
    "sentenceVi": "Những hoa hồng đỏ phát triển tươi tốt trong sân vườn.",
    "hint": "Từ vựng từ điển chuẩn (housing): sân vườn"
  },
  {
    "id": "vocab-97",
    "word": "rice",
    "ipa": "/raɪs/",
    "meaning": "cơm/gạo",
    "category": "food",
    "level": "basic",
    "image": "🍚",
    "sentence": "Steamed rice is a staple food.",
    "sentenceVi": "Cơm nóng là món ăn chính hàng ngày.",
    "hint": "Từ vựng từ điển chuẩn (food): cơm/gạo"
  },
  {
    "id": "vocab-98",
    "word": "noodle",
    "ipa": "/ˈnuː.dəl/",
    "meaning": "mì/phở",
    "category": "food",
    "level": "basic",
    "image": "🍜",
    "sentence": "Warm chicken noodles taste delicious.",
    "sentenceVi": "Mì gà nóng hổi có vị rất ngon.",
    "hint": "Từ vựng từ điển chuẩn (food): mì/phở"
  },
  {
    "id": "vocab-99",
    "word": "bread",
    "ipa": "/bred/",
    "meaning": "bánh mì",
    "category": "food",
    "level": "basic",
    "image": "🍞",
    "sentence": "Fresh bread rolls for breakfast.",
    "sentenceVi": "Những ổ bánh mì tươi cho bữa sáng.",
    "hint": "Từ vựng từ điển chuẩn (food): bánh mì"
  },
  {
    "id": "vocab-100",
    "word": "beef",
    "ipa": "/biːf/",
    "meaning": "thịt bò",
    "category": "food",
    "level": "elementary",
    "image": "🥩",
    "sentence": "Tender beef with vegetables.",
    "sentenceVi": "Thịt bò mềm xào cùng rau củ.",
    "hint": "Từ vựng từ điển chuẩn (food): thịt bò"
  },
  {
    "id": "vocab-101",
    "word": "chicken",
    "ipa": "/ˈtʃɪk.ɪn/",
    "meaning": "thịt gà",
    "category": "food",
    "level": "basic",
    "image": "🍗",
    "sentence": "Crispy fried chicken wings.",
    "sentenceVi": "Cánh gà rán giòn rụm.",
    "hint": "Từ vựng từ điển chuẩn (food): thịt gà"
  },
  {
    "id": "vocab-102",
    "word": "fish",
    "ipa": "/fɪʃ/",
    "meaning": "cá tươi",
    "category": "food",
    "level": "basic",
    "image": "🐟",
    "sentence": "Fresh fish is healthy food.",
    "sentenceVi": "Cá tươi là thực phẩm lành mạnh.",
    "hint": "Từ vựng từ điển chuẩn (food): cá tươi"
  },
  {
    "id": "vocab-103",
    "word": "water",
    "ipa": "/ˈwɔː.tər/",
    "meaning": "nước lọc",
    "category": "drinks",
    "level": "basic",
    "image": "💧",
    "sentence": "Drink fresh water throughout the day.",
    "sentenceVi": "Uống nước sạch đều đặn trong ngày.",
    "hint": "Từ vựng từ điển chuẩn (drinks): nước lọc"
  },
  {
    "id": "vocab-104",
    "word": "milk",
    "ipa": "/mɪlk/",
    "meaning": "sữa tươi",
    "category": "drinks",
    "level": "basic",
    "image": "🥛",
    "sentence": "A cup of warm milk before sleep.",
    "sentenceVi": "Một ly sữa ấm trước khi đi ngủ.",
    "hint": "Từ vựng từ điển chuẩn (drinks): sữa tươi"
  },
  {
    "id": "vocab-105",
    "word": "juice",
    "ipa": "/dʒuːs/",
    "meaning": "nước ép trái cây",
    "category": "drinks",
    "level": "basic",
    "image": "🧃",
    "sentence": "Sweet orange juice is full of Vitamin C.",
    "sentenceVi": "Nước ép cam ngọt chứa nhiều Vitamin C.",
    "hint": "Từ vựng từ điển chuẩn (drinks): nước ép trái cây"
  },
  {
    "id": "vocab-106",
    "word": "tea",
    "ipa": "/tiː/",
    "meaning": "trà thanh nhiệt",
    "category": "drinks",
    "level": "elementary",
    "image": "🍵",
    "sentence": "Herbal tea calms the mind.",
    "sentenceVi": "Trà thảo mộc giúp thư thái tâm trí.",
    "hint": "Từ vựng từ điển chuẩn (drinks): trà thanh nhiệt"
  },
  {
    "id": "vocab-107",
    "word": "smoothie",
    "ipa": "/ˈsmuː.ði/",
    "meaning": "sinh tố",
    "category": "drinks",
    "level": "elementary",
    "image": "🥤",
    "sentence": "Strawberry smoothie is cold and sweet.",
    "sentenceVi": "Sinh tố dâu tây mát lạnh và ngọt ngào.",
    "hint": "Từ vựng từ điển chuẩn (drinks): sinh tố"
  },
  {
    "id": "vocab-108",
    "word": "cook",
    "ipa": "/kʊk/",
    "meaning": "nấu ăn",
    "category": "cooking",
    "level": "basic",
    "image": "👨‍🍳",
    "sentence": "Cook a tasty meal for the family.",
    "sentenceVi": "Nấu một bữa ăn ngon cho gia đình.",
    "hint": "Từ vựng từ điển chuẩn (cooking): nấu ăn"
  },
  {
    "id": "vocab-109",
    "word": "boil",
    "ipa": "/bɔɪl/",
    "meaning": "luộc",
    "category": "cooking",
    "level": "basic",
    "image": "🍲",
    "sentence": "Boil fresh eggs for ten minutes.",
    "sentenceVi": "Luộc trứng tươi trong mười phút.",
    "hint": "Từ vựng từ điển chuẩn (cooking): luộc"
  },
  {
    "id": "vocab-110",
    "word": "fry",
    "ipa": "/fraɪ/",
    "meaning": "chiên/rán",
    "category": "cooking",
    "level": "basic",
    "image": "🍳",
    "sentence": "Fry potatoes until golden brown.",
    "sentenceVi": "Rán khoai tây cho đến khi chín vàng giòn.",
    "hint": "Từ vựng từ điển chuẩn (cooking): chiên/rán"
  },
  {
    "id": "vocab-111",
    "word": "bake",
    "ipa": "/beɪk/",
    "meaning": "nướng bánh",
    "category": "cooking",
    "level": "elementary",
    "image": "🥧",
    "sentence": "Bake a chocolate birthday cake.",
    "sentenceVi": "Nướng một chiếc bánh sinh nhật sô cô la.",
    "hint": "Từ vựng từ điển chuẩn (cooking): nướng bánh"
  },
  {
    "id": "vocab-112",
    "word": "slice",
    "ipa": "/slaɪs/",
    "meaning": "thái lát",
    "category": "cooking",
    "level": "elementary",
    "image": "🔪",
    "sentence": "Slice fresh tomatoes carefully.",
    "sentenceVi": "Thái lát cà chua tươi thật cẩn thận.",
    "hint": "Từ vựng từ điển chuẩn (cooking): thái lát"
  },
  {
    "id": "vocab-113",
    "word": "shirt",
    "ipa": "/ʃɜːt/",
    "meaning": "áo sơ mi",
    "category": "clothes",
    "level": "basic",
    "image": "👔",
    "sentence": "He wears a smart blue shirt.",
    "sentenceVi": "Anh ấy mặc chiếc áo sơ mi màu xanh lịch sự.",
    "hint": "Từ vựng từ điển chuẩn (clothes): áo sơ mi"
  },
  {
    "id": "vocab-114",
    "word": "tshirt",
    "ipa": "/ˈtiː.ʃɜːt/",
    "meaning": "áo thun",
    "category": "clothes",
    "level": "basic",
    "image": "👕",
    "sentence": "A cotton t-shirt for hot days.",
    "sentenceVi": "Áo thun cotton cho những ngày nắng nóng.",
    "hint": "Từ vựng từ điển chuẩn (clothes): áo thun"
  },
  {
    "id": "vocab-115",
    "word": "dress",
    "ipa": "/dres/",
    "meaning": "chiếc đầm/váy",
    "category": "clothes",
    "level": "basic",
    "image": "👗",
    "sentence": "Minh Anh wears a pretty pink dress.",
    "sentenceVi": "Minh Anh mặc chiếc đầm màu hồng xinh xắn.",
    "hint": "Từ vựng từ điển chuẩn (clothes): chiếc đầm/váy"
  },
  {
    "id": "vocab-116",
    "word": "jacket",
    "ipa": "/ˈdʒæk.ɪt/",
    "meaning": "áo khoác",
    "category": "clothes",
    "level": "elementary",
    "image": "🧥",
    "sentence": "Put on your jacket when it gets cold.",
    "sentenceVi": "Khoác áo vào khi trời trở lạnh.",
    "hint": "Từ vựng từ điển chuẩn (clothes): áo khoác"
  },
  {
    "id": "vocab-117",
    "word": "shoes",
    "ipa": "/ʃuːz/",
    "meaning": "đôi giày",
    "category": "clothes",
    "level": "basic",
    "image": "👟",
    "sentence": "Tie your shoes securely before running.",
    "sentenceVi": "Buộc chặt dây giày trước khi chạy.",
    "hint": "Từ vựng từ điển chuẩn (clothes): đôi giày"
  },
  {
    "id": "vocab-118",
    "word": "school",
    "ipa": "/skuːl/",
    "meaning": "trường học",
    "category": "school",
    "level": "basic",
    "image": "🏫",
    "sentence": "We go to school to gain knowledge.",
    "sentenceVi": "Chúng mình đến trường để tiếp thu kiến thức.",
    "hint": "Từ vựng từ điển chuẩn (school): trường học"
  },
  {
    "id": "vocab-119",
    "word": "classroom",
    "ipa": "/ˈklɑːs.ruːm/",
    "meaning": "lớp học",
    "category": "school",
    "level": "basic",
    "image": "🏫",
    "sentence": "Our classroom is clean and bright.",
    "sentenceVi": "Lớp học của chúng mình luôn sạch sẽ và sáng sủa.",
    "hint": "Từ vựng từ điển chuẩn (school): lớp học"
  },
  {
    "id": "vocab-120",
    "word": "teacher",
    "ipa": "/ˈtiː.tʃər/",
    "meaning": "giáo viên",
    "category": "school",
    "level": "basic",
    "image": "🧑‍🏫",
    "sentence": "Our teacher guides us patiently.",
    "sentenceVi": "Cô giáo kiên nhẫn hướng dẫn chúng mình.",
    "hint": "Từ vựng từ điển chuẩn (school): giáo viên"
  },
  {
    "id": "vocab-121",
    "word": "student",
    "ipa": "/ˈstjuː.dənt/",
    "meaning": "học sinh",
    "category": "school",
    "level": "basic",
    "image": "🧑‍🎓",
    "sentence": "Every student listens attentively.",
    "sentenceVi": "Mỗi học sinh đều chăm chú lắng nghe.",
    "hint": "Từ vựng từ điển chuẩn (school): học sinh"
  },
  {
    "id": "vocab-122",
    "word": "library",
    "ipa": "/ˈlaɪ.brər.i/",
    "meaning": "thư viện",
    "category": "school",
    "level": "elementary",
    "image": "📖",
    "sentence": "Find quiet books in the school library.",
    "sentenceVi": "Tìm đọc những cuốn sách hay trong thư viện trường.",
    "hint": "Từ vựng từ điển chuẩn (school): thư viện"
  },
  {
    "id": "vocab-123",
    "word": "book",
    "ipa": "/bʊk/",
    "meaning": "cuốn sách",
    "category": "supplies",
    "level": "basic",
    "image": "📚",
    "sentence": "Read an inspiring storybook.",
    "sentenceVi": "Đọc một cuốn sách truyện truyền cảm hứng.",
    "hint": "Từ vựng từ điển chuẩn (supplies): cuốn sách"
  },
  {
    "id": "vocab-124",
    "word": "notebook",
    "ipa": "/ˈnəʊt.bʊk/",
    "meaning": "quyển vở",
    "category": "supplies",
    "level": "basic",
    "image": "📓",
    "sentence": "Write your notes neatly in the notebook.",
    "sentenceVi": "Viết ghi chú gọn gàng vào quyển vở.",
    "hint": "Từ vựng từ điển chuẩn (supplies): quyển vở"
  },
  {
    "id": "vocab-125",
    "word": "pencil",
    "ipa": "/ˈpen.səl/",
    "meaning": "bút chì",
    "category": "supplies",
    "level": "basic",
    "image": "✏️",
    "sentence": "Sharpen your pencil before writing.",
    "sentenceVi": "Gọt bút chì sắc trước khi viết.",
    "hint": "Từ vựng từ điển chuẩn (supplies): bút chì"
  },
  {
    "id": "vocab-126",
    "word": "ruler",
    "ipa": "/ˈruː.lər/",
    "meaning": "thước kẻ",
    "category": "supplies",
    "level": "basic",
    "image": "📏",
    "sentence": "Draw straight lines using a ruler.",
    "sentenceVi": "Kẻ đường thẳng bằng thước kẻ.",
    "hint": "Từ vựng từ điển chuẩn (supplies): thước kẻ"
  },
  {
    "id": "vocab-127",
    "word": "eraser",
    "ipa": "/ɪˈreɪ.zər/",
    "meaning": "cục tẩy",
    "category": "supplies",
    "level": "basic",
    "image": "🧹",
    "sentence": "Erase pencil marks with an eraser.",
    "sentenceVi": "Tẩy vết bút chì bằng cục tẩy.",
    "hint": "Từ vựng từ điển chuẩn (supplies): cục tẩy"
  },
  {
    "id": "vocab-128",
    "word": "backpack",
    "ipa": "/ˈbæk.pæk/",
    "meaning": "ba lô học sinh",
    "category": "supplies",
    "level": "basic",
    "image": "🎒",
    "sentence": "Carry your school supplies in a backpack.",
    "sentenceVi": "Đựng đồ dùng học tập trong chiếc ba lô.",
    "hint": "Từ vựng từ điển chuẩn (supplies): ba lô học sinh"
  },
  {
    "id": "vocab-129",
    "word": "english",
    "ipa": "/ˈɪŋ.ɡlɪʃ/",
    "meaning": "môn tiếng Anh",
    "category": "subjects",
    "level": "basic",
    "image": "🇬🇧",
    "sentence": "Minh Anh speaks fluent English.",
    "sentenceVi": "Minh Anh nói tiếng Anh rất lưu khoát.",
    "hint": "Từ vựng từ điển chuẩn (subjects): môn tiếng Anh"
  },
  {
    "id": "vocab-130",
    "word": "maths",
    "ipa": "/mæθs/",
    "meaning": "môn toán",
    "category": "subjects",
    "level": "basic",
    "image": "🔢",
    "sentence": "Maths helps develop logical thinking.",
    "sentenceVi": "Môn toán giúp phát triển tư duy logic.",
    "hint": "Từ vựng từ điển chuẩn (subjects): môn toán"
  },
  {
    "id": "vocab-131",
    "word": "science",
    "ipa": "/ˈsaɪ.əns/",
    "meaning": "môn khoa học",
    "category": "subjects",
    "level": "elementary",
    "image": "🔬",
    "sentence": "Science experiments are exciting.",
    "sentenceVi": "Các thí nghiệm khoa học vô cùng thú vị.",
    "hint": "Từ vựng từ điển chuẩn (subjects): môn khoa học"
  },
  {
    "id": "vocab-132",
    "word": "history",
    "ipa": "/ˈhɪs.tər.i/",
    "meaning": "môn lịch sử",
    "category": "subjects",
    "level": "elementary",
    "image": "📜",
    "sentence": "Learn about past heroes in history.",
    "sentenceVi": "Học về các vị anh hùng quá khứ trong môn lịch sử.",
    "hint": "Từ vựng từ điển chuẩn (subjects): môn lịch sử"
  },
  {
    "id": "vocab-133",
    "word": "geography",
    "ipa": "/dʒiˈɒɡ.rə.fi/",
    "meaning": "môn địa lý",
    "category": "subjects",
    "level": "elementary",
    "image": "🗺️",
    "sentence": "Study world maps in geography class.",
    "sentenceVi": "Học bản đồ thế giới trong giờ địa lý.",
    "hint": "Từ vựng từ điển chuẩn (subjects): môn địa lý"
  },
  {
    "id": "vocab-134",
    "word": "doll",
    "ipa": "/dɒl/",
    "meaning": "búp bê",
    "category": "toys",
    "level": "basic",
    "image": "🪆",
    "sentence": "A cute doll with golden hair.",
    "sentenceVi": "Chú búp bê đáng yêu với mái tóc vàng.",
    "hint": "Từ vựng từ điển chuẩn (toys): búp bê"
  },
  {
    "id": "vocab-135",
    "word": "robot",
    "ipa": "/ˈrəʊ.bɒt/",
    "meaning": "người máy",
    "category": "toys",
    "level": "basic",
    "image": "🤖",
    "sentence": "A toy robot that walks and speaks.",
    "sentenceVi": "Robot đồ chơi biết đi và biết nói.",
    "hint": "Từ vựng từ điển chuẩn (toys): người máy"
  },
  {
    "id": "vocab-136",
    "word": "puzzle",
    "ipa": "/ˈpʌz.əl/",
    "meaning": "trò chơi ghép hình",
    "category": "toys",
    "level": "elementary",
    "image": "🧩",
    "sentence": "Complete a 500-piece landscape puzzle.",
    "sentenceVi": "Hoàn thành bức tranh ghép hình 500 mảnh.",
    "hint": "Từ vựng từ điển chuẩn (toys): trò chơi ghép hình"
  },
  {
    "id": "vocab-137",
    "word": "ball",
    "ipa": "/bɔːl/",
    "meaning": "quả bóng",
    "category": "toys",
    "level": "basic",
    "image": "⚽",
    "sentence": "Bounce the rubber ball high.",
    "sentenceVi": "Tâng quả bóng cao lên.",
    "hint": "Từ vựng từ điển chuẩn (toys): quả bóng"
  },
  {
    "id": "vocab-138",
    "word": "kite",
    "ipa": "/kaɪt/",
    "meaning": "con diều",
    "category": "toys",
    "level": "basic",
    "image": "🪁",
    "sentence": "Fly a colorful kite in the windy field.",
    "sentenceVi": "Thả con diều rực rỡ trên cánh đồng lộng gió.",
    "hint": "Từ vựng từ điển chuẩn (toys): con diều"
  },
  {
    "id": "vocab-139",
    "word": "dog",
    "ipa": "/dɒɡ/",
    "meaning": "con chó",
    "category": "animals",
    "level": "basic",
    "image": "🐶",
    "sentence": "The loyal dog barks happily.",
    "sentenceVi": "Chú chó trung thành sủa vui vẻ.",
    "hint": "Từ vựng từ điển chuẩn (animals): con chó"
  },
  {
    "id": "vocab-140",
    "word": "cat",
    "ipa": "/kæt/",
    "meaning": "con mèo",
    "category": "animals",
    "level": "basic",
    "image": "🐱",
    "sentence": "The soft cat purrs on the cushion.",
    "sentenceVi": "Chú mèo mềm mại kêu meo meo trên nệm.",
    "hint": "Từ vựng từ điển chuẩn (animals): con mèo"
  },
  {
    "id": "vocab-141",
    "word": "lion",
    "ipa": "/ˈlaɪ.ən/",
    "meaning": "con sư tử",
    "category": "animals",
    "level": "basic",
    "image": "🦁",
    "sentence": "The lion roars loudly in the savanna.",
    "sentenceVi": "Sư tử rống to trên đồng cỏ.",
    "hint": "Từ vựng từ điển chuẩn (animals): con sư tử"
  },
  {
    "id": "vocab-142",
    "word": "tiger",
    "ipa": "/ˈtaɪ.ɡər/",
    "meaning": "con hổ",
    "category": "animals",
    "level": "basic",
    "image": "🐯",
    "sentence": "A tiger has orange stripes.",
    "sentenceVi": "Con hổ có những vằn màu cam.",
    "hint": "Từ vựng từ điển chuẩn (animals): con hổ"
  },
  {
    "id": "vocab-143",
    "word": "elephant",
    "ipa": "/ˈel.ɪ.fənt/",
    "meaning": "con voi",
    "category": "animals",
    "level": "basic",
    "image": "🐘",
    "sentence": "An elephant sprays water with its trunk.",
    "sentenceVi": "Con voi phun nước bằng cái vòi dài.",
    "hint": "Từ vựng từ điển chuẩn (animals): con voi"
  },
  {
    "id": "vocab-144",
    "word": "dolphin",
    "ipa": "/ˈdɒl.fɪn/",
    "meaning": "con cá heo",
    "category": "animals",
    "level": "basic",
    "image": "🐬",
    "sentence": "Friendly dolphins leap out of the ocean.",
    "sentenceVi": "Những chú cá heo thân thiện nhảy lên khỏi mặt biển.",
    "hint": "Từ vựng từ điển chuẩn (animals): con cá heo"
  },
  {
    "id": "vocab-145",
    "word": "tree",
    "ipa": "/triː/",
    "meaning": "cây xanh",
    "category": "nature",
    "level": "basic",
    "image": "🌳",
    "sentence": "Tall green trees offer cool shade.",
    "sentenceVi": "Cây xanh cao vút mang lại bóng mát.",
    "hint": "Từ vựng từ điển chuẩn (nature): cây xanh"
  },
  {
    "id": "vocab-146",
    "word": "flower",
    "ipa": "/flaʊ.ər/",
    "meaning": "bông hoa",
    "category": "nature",
    "level": "basic",
    "image": "🌸",
    "sentence": "Red flowers bloom in spring.",
    "sentenceVi": "Những bông hoa đỏ nở rộ vào mùa xuân.",
    "hint": "Từ vựng từ điển chuẩn (nature): bông hoa"
  },
  {
    "id": "vocab-147",
    "word": "forest",
    "ipa": "/ˈfɒr.ɪst/",
    "meaning": "khu rừng",
    "category": "nature",
    "level": "elementary",
    "image": "🌲",
    "sentence": "Wild animals live safely in the forest.",
    "sentenceVi": "Động vật hoang dã sống an toàn trong khu rừng.",
    "hint": "Từ vựng từ điển chuẩn (nature): khu rừng"
  },
  {
    "id": "vocab-148",
    "word": "mountain",
    "ipa": "/ˈmaʊn.tɪn/",
    "meaning": "ngọn núi",
    "category": "nature",
    "level": "elementary",
    "image": "⛰️",
    "sentence": "The snow-capped mountain reaches the clouds.",
    "sentenceVi": "Ngọn núi phủ tuyết chạm tới những tầng mây.",
    "hint": "Từ vựng từ điển chuẩn (nature): ngọn núi"
  },
  {
    "id": "vocab-149",
    "word": "river",
    "ipa": "/ˈrɪv.ər/",
    "meaning": "dòng sông",
    "category": "nature",
    "level": "elementary",
    "image": "🏞️",
    "sentence": "Fresh river water flows calmly.",
    "sentenceVi": "Nước sông tươi mát chảy êm đềm.",
    "hint": "Từ vựng từ điển chuẩn (nature): dòng sông"
  },
  {
    "id": "vocab-150",
    "word": "ocean",
    "ipa": "/ˈəʊ.ʃən/",
    "meaning": "đại dương",
    "category": "nature",
    "level": "elementary",
    "image": "🌊",
    "sentence": "The deep blue ocean is full of marine life.",
    "sentenceVi": "Đại dương xanh thẫm tràn ngập sinh vật biển.",
    "hint": "Từ vựng từ điển chuẩn (nature): đại dương"
  },
  {
    "id": "vocab-151",
    "word": "sunny",
    "ipa": "/ˈsʌn.i/",
    "meaning": "trời nắng",
    "category": "weather",
    "level": "basic",
    "image": "☀️",
    "sentence": "It is a warm sunny day for playing.",
    "sentenceVi": "Một ngày nắng ấm áp thích hợp để vui chơi.",
    "hint": "Từ vựng từ điển chuẩn (weather): trời nắng"
  },
  {
    "id": "vocab-152",
    "word": "rainy",
    "ipa": "/ˈreɪ.ni/",
    "meaning": "trời mưa",
    "category": "weather",
    "level": "basic",
    "image": "🌧️",
    "sentence": "Take an umbrella on rainy days.",
    "sentenceVi": "Mang theo chiếc dù vào những ngày mưa.",
    "hint": "Từ vựng từ điển chuẩn (weather): trời mưa"
  },
  {
    "id": "vocab-153",
    "word": "cloudy",
    "ipa": "/ˈklaʊ.di/",
    "meaning": "nhiều mây",
    "category": "weather",
    "level": "basic",
    "image": "☁️",
    "sentence": "The cloudy sky shelters us from heat.",
    "sentenceVi": "Bầu trời nhiều mây che bớt hơi nóng.",
    "hint": "Từ vựng từ điển chuẩn (weather): nhiều mây"
  },
  {
    "id": "vocab-154",
    "word": "windy",
    "ipa": "/ˈwɪn.di/",
    "meaning": "nhiều gió",
    "category": "weather",
    "level": "basic",
    "image": "🌬️",
    "sentence": "A cool windy breeze in autumn.",
    "sentenceVi": "Làn gió mát lành vào mùa thu.",
    "hint": "Từ vựng từ điển chuẩn (weather): nhiều gió"
  },
  {
    "id": "vocab-155",
    "word": "snowy",
    "ipa": "/ˈsnəʊ.i/",
    "meaning": "có tuyết rơi",
    "category": "weather",
    "level": "elementary",
    "image": "❄️",
    "sentence": "We build a snowman on snowy days.",
    "sentenceVi": "Chúng mình làm người tuyết vào ngày có tuyết rơi.",
    "hint": "Từ vựng từ điển chuẩn (weather): có tuyết rơi"
  },
  {
    "id": "vocab-156",
    "word": "spring",
    "ipa": "/sprɪŋ/",
    "meaning": "mùa xuân",
    "category": "seasons",
    "level": "basic",
    "image": "🌸",
    "sentence": "Birds sing happily in spring.",
    "sentenceVi": "Chim chóc hót vui ca vào mùa xuân.",
    "hint": "Từ vựng từ điển chuẩn (seasons): mùa xuân"
  },
  {
    "id": "vocab-157",
    "word": "summer",
    "ipa": "/ˈsʌm.ər/",
    "meaning": "mùa hè",
    "category": "seasons",
    "level": "basic",
    "image": "☀️",
    "sentence": "Go swimming during summer break.",
    "sentenceVi": "Đi bơi trong kỳ nghỉ hè.",
    "hint": "Từ vựng từ điển chuẩn (seasons): mùa hè"
  },
  {
    "id": "vocab-158",
    "word": "autumn",
    "ipa": "/ˈɔː.təm/",
    "meaning": "mùa thu",
    "category": "seasons",
    "level": "basic",
    "image": "🍂",
    "sentence": "Golden leaves fall gently in autumn.",
    "sentenceVi": "Lá vàng rơi nhẹ nhàng vào mùa thu.",
    "hint": "Từ vựng từ điển chuẩn (seasons): mùa thu"
  },
  {
    "id": "vocab-159",
    "word": "winter",
    "ipa": "/ˈwɪn.tər/",
    "meaning": "mùa đông",
    "category": "seasons",
    "level": "basic",
    "image": "❄️",
    "sentence": "Wear warm coats during cold winter.",
    "sentenceVi": "Mặc áo ấm trong mùa đông lạnh giá.",
    "hint": "Từ vựng từ điển chuẩn (seasons): mùa đông"
  },
  {
    "id": "vocab-160",
    "word": "second",
    "ipa": "/ˈsek.ənd/",
    "meaning": "giây",
    "category": "time",
    "level": "basic",
    "image": "⏱️",
    "sentence": "Sixty seconds make one minute.",
    "sentenceVi": "Sáu mươi giây tạo thành một phút.",
    "hint": "Từ vựng từ điển chuẩn (time): giây"
  },
  {
    "id": "vocab-161",
    "word": "minute",
    "ipa": "/ˈmɪn.ɪt/",
    "meaning": "phút",
    "category": "time",
    "level": "basic",
    "image": "⏲️",
    "sentence": "Wait five minutes for the bus.",
    "sentenceVi": "Chờ xe buýt trong năm phút.",
    "hint": "Từ vựng từ điển chuẩn (time): phút"
  },
  {
    "id": "vocab-162",
    "word": "hour",
    "ipa": "/aʊər/",
    "meaning": "giờ",
    "category": "time",
    "level": "basic",
    "image": "⏰",
    "sentence": "Study for one hour each evening.",
    "sentenceVi": "Học bài trong một giờ mỗi buổi tối.",
    "hint": "Từ vựng từ điển chuẩn (time): giờ"
  },
  {
    "id": "vocab-163",
    "word": "today",
    "ipa": "/təˈdeɪ/",
    "meaning": "hôm nay",
    "category": "time",
    "level": "basic",
    "image": "📅",
    "sentence": "Today is a wonderful day to learn.",
    "sentenceVi": "Hôm nay là một ngày tuyệt vời để học tập.",
    "hint": "Từ vựng từ điển chuẩn (time): hôm nay"
  },
  {
    "id": "vocab-164",
    "word": "tomorrow",
    "ipa": "/təˈmɒr.əʊ/",
    "meaning": "ngày mai",
    "category": "time",
    "level": "basic",
    "image": "🌅",
    "sentence": "Tomorrow brings new adventures.",
    "sentenceVi": "Ngày mai mang đến những cuộc phiêu lưu mới.",
    "hint": "Từ vựng từ điển chuẩn (time): ngày mai"
  },
  {
    "id": "vocab-165",
    "word": "bicycle",
    "ipa": "/ˈbaɪ.sɪ.kəl/",
    "meaning": "xe đạp",
    "category": "transport",
    "level": "basic",
    "image": "🚲",
    "sentence": "Ride a bicycle safely on the track.",
    "sentenceVi": "Đạp xe an toàn trên làn đường.",
    "hint": "Từ vựng từ điển chuẩn (transport): xe đạp"
  },
  {
    "id": "vocab-166",
    "word": "car",
    "ipa": "/kɑːr/",
    "meaning": "xe ô tô",
    "category": "transport",
    "level": "basic",
    "image": "🚗",
    "sentence": "Father drives an electric car.",
    "sentenceVi": "Bố lái một chiếc xe ô tô điện.",
    "hint": "Từ vựng từ điển chuẩn (transport): xe ô tô"
  },
  {
    "id": "vocab-167",
    "word": "bus",
    "ipa": "/bʌs/",
    "meaning": "xe buýt",
    "category": "transport",
    "level": "basic",
    "image": "🚌",
    "sentence": "The school bus arrives on time.",
    "sentenceVi": "Xe buýt trường học đến đúng giờ.",
    "hint": "Từ vựng từ điển chuẩn (transport): xe buýt"
  },
  {
    "id": "vocab-168",
    "word": "train",
    "ipa": "/treɪn/",
    "meaning": "tàu hỏa",
    "category": "transport",
    "level": "basic",
    "image": "🚂",
    "sentence": "The express train glides on rails.",
    "sentenceVi": "Tàu hỏa tốc hành lướt trên đường ray.",
    "hint": "Từ vựng từ điển chuẩn (transport): tàu hỏa"
  },
  {
    "id": "vocab-169",
    "word": "airplane",
    "ipa": "/ˈeə.pleɪn/",
    "meaning": "máy bay",
    "category": "transport",
    "level": "basic",
    "image": "✈️",
    "sentence": "An airplane flies above clouds.",
    "sentenceVi": "Máy bay bay phía trên những tầng mây.",
    "hint": "Từ vựng từ điển chuẩn (transport): máy bay"
  },
  {
    "id": "vocab-170",
    "word": "park",
    "ipa": "/pɑːk/",
    "meaning": "công viên",
    "category": "places",
    "level": "basic",
    "image": "🏞️",
    "sentence": "Children play happily in the park.",
    "sentenceVi": "Trẻ em vui chơi thỏa thích trong công viên.",
    "hint": "Từ vựng từ điển chuẩn (places): công viên"
  },
  {
    "id": "vocab-171",
    "word": "museum",
    "ipa": "/mjuːˈziː.əm/",
    "meaning": "bảo tàng",
    "category": "places",
    "level": "elementary",
    "image": "🏛️",
    "sentence": "See ancient dinosaur bones at the museum.",
    "sentenceVi": "Ngắm bộ xương khủng long cổ đại ở bảo tàng.",
    "hint": "Từ vựng từ điển chuẩn (places): bảo tàng"
  },
  {
    "id": "vocab-172",
    "word": "supermarket",
    "ipa": "/ˈsuː.pəˌmɑː.kɪt/",
    "meaning": "siêu thị",
    "category": "places",
    "level": "basic",
    "image": "🛒",
    "sentence": "Buy fresh fruits at the supermarket.",
    "sentenceVi": "Mua trái cây tươi tại siêu thị.",
    "hint": "Từ vựng từ điển chuẩn (places): siêu thị"
  },
  {
    "id": "vocab-173",
    "word": "actress",
    "ipa": "/ˈæk.trəs/",
    "meaning": "nữ diễn viên",
    "category": "jobs",
    "level": "elementary",
    "image": "🎭",
    "sentence": "She is a talented film actress.",
    "sentenceVi": "Cô ấy là một nữ diễn viên điện ảnh tài năng.",
    "hint": "Từ vựng từ điển chuẩn (jobs): nữ diễn viên"
  },
  {
    "id": "vocab-174",
    "word": "actor",
    "ipa": "/ˈæk.tər/",
    "meaning": "nam diễn viên",
    "category": "jobs",
    "level": "elementary",
    "image": "🎭",
    "sentence": "The actor performs on stage.",
    "sentenceVi": "Nam diễn viên biểu diễn trên sân khấu.",
    "hint": "Từ vựng từ điển chuẩn (jobs): nam diễn viên"
  },
  {
    "id": "vocab-175",
    "word": "firefighter",
    "ipa": "/ˈfaɪəˌfaɪ.tər/",
    "meaning": "lính cứu hỏa",
    "category": "jobs",
    "level": "basic",
    "image": "👨‍🚒",
    "sentence": "Brave firefighters put out dangerous fires.",
    "sentenceVi": "Lính cứu hỏa dũng cảm dập tắt đám cháy hiểm nguy.",
    "hint": "Từ vựng từ điển chuẩn (jobs): lính cứu hỏa"
  },
  {
    "id": "vocab-176",
    "word": "chef",
    "ipa": "/ʃef/",
    "meaning": "đầu bếp",
    "category": "jobs",
    "level": "elementary",
    "image": "👨‍🍳",
    "sentence": "The chef prepares delicious meals.",
    "sentenceVi": "Đầu bếp chuẩn bị những bữa ăn tuyệt vời.",
    "hint": "Từ vựng từ điển chuẩn (jobs): đầu bếp"
  },
  {
    "id": "vocab-177",
    "word": "money",
    "ipa": "/ˈmʌn.i/",
    "meaning": "tiền bạc",
    "category": "shopping",
    "level": "basic",
    "image": "💵",
    "sentence": "Save money inside a piggy bank.",
    "sentenceVi": "Tiết kiệm tiền trong con heo đất.",
    "hint": "Từ vựng từ điển chuẩn (shopping): tiền bạc"
  },
  {
    "id": "vocab-178",
    "word": "price",
    "ipa": "/praɪs/",
    "meaning": "mức giá",
    "category": "shopping",
    "level": "basic",
    "image": "🏷️",
    "sentence": "Check the item price tag.",
    "sentenceVi": "Kiểm tra nhãn giá sản phẩm.",
    "hint": "Từ vựng từ điển chuẩn (shopping): mức giá"
  },
  {
    "id": "vocab-179",
    "word": "discount",
    "ipa": "/ˈdɪs.kaʊnt/",
    "meaning": "sự giảm giá",
    "category": "shopping",
    "level": "elementary",
    "image": "🎉",
    "sentence": "Enjoy special holiday discounts.",
    "sentenceVi": "Tận hưởng ưu đãi giảm giá đặc biệt dịp lễ.",
    "hint": "Từ vựng từ điển chuẩn (shopping): sự giảm giá"
  },
  {
    "id": "vocab-180",
    "word": "receipt",
    "ipa": "/rɪˈsiːt/",
    "meaning": "biên lai",
    "category": "shopping",
    "level": "elementary",
    "image": "📃",
    "sentence": "Keep your shopping receipt for reference.",
    "sentenceVi": "Giữ biên lai mua sắm để đối chiếu.",
    "hint": "Từ vựng từ điển chuẩn (shopping): biên lai"
  },
  {
    "id": "vocab-181",
    "word": "passport",
    "ipa": "/ˈpɑːs.pɔːt/",
    "meaning": "hộ chiếu",
    "category": "travel",
    "level": "elementary",
    "image": "🛂",
    "sentence": "Show your passport at airport security.",
    "sentenceVi": "Xuất trình hộ chiếu tại an ninh sân bay.",
    "hint": "Từ vựng từ điển chuẩn (travel): hộ chiếu"
  },
  {
    "id": "vocab-182",
    "word": "luggage",
    "ipa": "/ˈlʌɡ.ɪdʒ/",
    "meaning": "hành lý",
    "category": "travel",
    "level": "elementary",
    "image": "🧳",
    "sentence": "Pack your travel luggage neatly.",
    "sentenceVi": "Gói gọn hành lý du lịch.",
    "hint": "Từ vựng từ điển chuẩn (travel): hành lý"
  },
  {
    "id": "vocab-183",
    "word": "adventure",
    "ipa": "/ədˈven.tʃər/",
    "meaning": "cuộc phiêu lưu",
    "category": "travel",
    "level": "intermediate",
    "image": "🧭",
    "sentence": "An exciting mountain climbing adventure.",
    "sentenceVi": "Một cuộc phiêu lưu leo núi kịch tính.",
    "hint": "Từ vựng từ điển chuẩn (travel): cuộc phiêu lưu"
  },
  {
    "id": "vocab-184",
    "word": "soccer",
    "ipa": "/ˈsɒk.ər/",
    "meaning": "môn bóng đá",
    "category": "sports",
    "level": "basic",
    "image": "⚽",
    "sentence": "Play soccer with your teammates.",
    "sentenceVi": "Chơi bóng đá cùng đồng đội.",
    "hint": "Từ vựng từ điển chuẩn (sports): môn bóng đá"
  },
  {
    "id": "vocab-185",
    "word": "swimming",
    "ipa": "/ˈswɪm.ɪŋ/",
    "meaning": "môn bơi lội",
    "category": "sports",
    "level": "basic",
    "image": "🏊",
    "sentence": "Swimming builds strong muscles.",
    "sentenceVi": "Bơi lội giúp rèn luyện cơ thể dẻo dai.",
    "hint": "Từ vựng từ điển chuẩn (sports): môn bơi lội"
  },
  {
    "id": "vocab-186",
    "word": "tennis",
    "ipa": "/ˈten.ɪs/",
    "meaning": "môn quần vợt",
    "category": "sports",
    "level": "elementary",
    "image": "🎾",
    "sentence": "Hit the tennis ball across the net.",
    "sentenceVi": "Đánh quả bóng quần vợt qua lưới.",
    "hint": "Từ vựng từ điển chuẩn (sports): môn quần vợt"
  },
  {
    "id": "vocab-187",
    "word": "running",
    "ipa": "/ˈrʌn.ɪŋ/",
    "meaning": "chạy bộ",
    "category": "sports",
    "level": "basic",
    "image": "🏃",
    "sentence": "Morning running gives great energy.",
    "sentenceVi": "Chạy bộ buổi sáng mang lại năng lượng tràn trề.",
    "hint": "Từ vựng từ điển chuẩn (sports): chạy bộ"
  },
  {
    "id": "vocab-188",
    "word": "reading",
    "ipa": "/ˈriː.dɪŋ/",
    "meaning": "đọc sách",
    "category": "hobbies",
    "level": "basic",
    "image": "📖",
    "sentence": "Reading expands your mind.",
    "sentenceVi": "Đọc sách giúp mở rộng trí tuệ.",
    "hint": "Từ vựng từ điển chuẩn (hobbies): đọc sách"
  },
  {
    "id": "vocab-189",
    "word": "painting",
    "ipa": "/ˈpeɪn.tɪŋ/",
    "meaning": "vẽ tranh",
    "category": "hobbies",
    "level": "basic",
    "image": "🎨",
    "sentence": "Painting vibrant watercolor landscapes.",
    "sentenceVi": "Vẽ những bức tranh phong cảnh màu nước rực rỡ.",
    "hint": "Từ vựng từ điển chuẩn (hobbies): vẽ tranh"
  },
  {
    "id": "vocab-190",
    "word": "singing",
    "ipa": "/ˈsɪŋ.ɪŋ/",
    "meaning": "ca hát",
    "category": "hobbies",
    "level": "basic",
    "image": "🎤",
    "sentence": "Singing melodic songs brings joy.",
    "sentenceVi": "Hát những bài hát du dương mang lại niềm vui.",
    "hint": "Từ vựng từ điển chuẩn (hobbies): ca hát"
  },
  {
    "id": "vocab-191",
    "word": "music",
    "ipa": "/ˈmjuː.zɪk/",
    "meaning": "âm nhạc",
    "category": "art",
    "level": "basic",
    "image": "🎶",
    "sentence": "Gentle music relaxes your mind.",
    "sentenceVi": "Âm nhạc dịu nhẹ giúp tâm hồn thư thái.",
    "hint": "Từ vựng từ điển chuẩn (art): âm nhạc"
  },
  {
    "id": "vocab-192",
    "word": "cinema",
    "ipa": "/ˈsɪn.ə.mɑː/",
    "meaning": "rạp chiếu phim",
    "category": "art",
    "level": "basic",
    "image": "🎬",
    "sentence": "Watch an animated movie at the cinema.",
    "sentenceVi": "Xem phim hoạt hình tại rạp chiếu phim.",
    "hint": "Từ vựng từ điển chuẩn (art): rạp chiếu phim"
  },
  {
    "id": "vocab-193",
    "word": "orchestra",
    "ipa": "/ˈɔː.kɪ.strə/",
    "meaning": "dàn nhạc giao hưởng",
    "category": "art",
    "level": "intermediate",
    "image": "🎷",
    "sentence": "The orchestra plays classical symphonies.",
    "sentenceVi": "Dàn nhạc giao hưởng trình diễn các bản hòa tấu cổ điển.",
    "hint": "Từ vựng từ điển chuẩn (art): dàn nhạc giao hưởng"
  },
  {
    "id": "vocab-194",
    "word": "computer",
    "ipa": "/kəmˈpjuː.tər/",
    "meaning": "máy tính",
    "category": "tech",
    "level": "basic",
    "image": "💻",
    "sentence": "Learn coding logic on a computer.",
    "sentenceVi": "Học tư duy lập trình trên máy tính.",
    "hint": "Từ vựng từ điển chuẩn (tech): máy tính"
  },
  {
    "id": "vocab-195",
    "word": "internet",
    "ipa": "/ˈɪn.tə.net/",
    "meaning": "mạng internet",
    "category": "tech",
    "level": "basic",
    "image": "🌐",
    "sentence": "The internet connects global learners.",
    "sentenceVi": "Mạng internet kết nối người học toàn cầu.",
    "hint": "Từ vựng từ điển chuẩn (tech): mạng internet"
  },
  {
    "id": "vocab-196",
    "word": "robotics",
    "ipa": "/rəʊˈbɒt.ɪks/",
    "meaning": "công nghệ robot",
    "category": "tech",
    "level": "intermediate",
    "image": "🤖",
    "sentence": "Robotics changes modern industry.",
    "sentenceVi": "Công nghệ robot làm thay đổi ngành công nghiệp hiện đại.",
    "hint": "Từ vựng từ điển chuẩn (tech): công nghệ robot"
  },
  {
    "id": "vocab-197",
    "word": "hello",
    "ipa": "/həˈləʊ/",
    "meaning": "lời chào",
    "category": "communication",
    "level": "basic",
    "image": "👋",
    "sentence": "Say hello with a friendly smile.",
    "sentenceVi": "Nói lời chào bằng nụ cười thân thiện.",
    "hint": "Từ vựng từ điển chuẩn (communication): lời chào"
  },
  {
    "id": "vocab-198",
    "word": "goodbye",
    "ipa": "/ɡʊdˈbaɪ/",
    "meaning": "lời tạm biệt",
    "category": "communication",
    "level": "basic",
    "image": "👋",
    "sentence": "Wave goodbye to your friends.",
    "sentenceVi": "Vẫy tay tạm biệt bạn bè.",
    "hint": "Từ vựng từ điển chuẩn (communication): lời tạm biệt"
  },
  {
    "id": "vocab-199",
    "word": "thankyou",
    "ipa": "/ˈθæŋk ˌjuː/",
    "meaning": "lời cảm ơn",
    "category": "communication",
    "level": "basic",
    "image": "🙏",
    "sentence": "Always say thank you when helped.",
    "sentenceVi": "Luôn nói cảm ơn khi được nhận sự giúp đỡ.",
    "hint": "Từ vựng từ điển chuẩn (communication): lời cảm ơn"
  },
  {
    "id": "vocab-200",
    "word": "sorry",
    "ipa": "/ˈsɒr.i/",
    "meaning": "lời xin lỗi",
    "category": "communication",
    "level": "basic",
    "image": "💔",
    "sentence": "Say sorry if you make a mistake.",
    "sentenceVi": "Nói xin lỗi khi con phạm sai lầm.",
    "hint": "Từ vựng từ điển chuẩn (communication): lời xin lỗi"
  },
  {
    "id": "vocab-201",
    "word": "christmas",
    "ipa": "/ˈkrɪs.məs/",
    "meaning": "lễ Giáng sinh",
    "category": "festivals",
    "level": "basic",
    "image": "🎄",
    "sentence": "Receive gifts under the Christmas tree.",
    "sentenceVi": "Nhận quà dưới cây thông Giáng sinh.",
    "hint": "Từ vựng từ điển chuẩn (festivals): lễ Giáng sinh"
  },
  {
    "id": "vocab-202",
    "word": "halloween",
    "ipa": "/ˌhæl.əʊˈiːn/",
    "meaning": "lễ Halloween",
    "category": "festivals",
    "level": "elementary",
    "image": "🎃",
    "sentence": "Carve pumpkin lanterns for Halloween.",
    "sentenceVi": "Tỉa đèn lồng bí ngô cho lễ Halloween.",
    "hint": "Từ vựng từ điển chuẩn (festivals): lễ Halloween"
  },
  {
    "id": "vocab-203",
    "word": "vietnam",
    "ipa": "/ˌvjetˈnæm/",
    "meaning": "đất nước Việt Nam",
    "category": "culture",
    "level": "basic",
    "image": "🇻🇳",
    "sentence": "Vietnam has rich cultural traditions.",
    "sentenceVi": "Việt Nam có bề dày truyền thống văn hóa phong phú.",
    "hint": "Từ vựng từ điển chuẩn (culture): đất nước Việt Nam"
  },
  {
    "id": "vocab-204",
    "word": "culture",
    "ipa": "/ˈkʌl.tʃər/",
    "meaning": "nền văn hóa",
    "category": "culture",
    "level": "elementary",
    "image": "⛩️",
    "sentence": "Respect different world cultures.",
    "sentenceVi": "Tôn trọng các nền văn hóa khác nhau trên thế giới.",
    "hint": "Từ vựng từ điển chuẩn (culture): nền văn hóa"
  },
  {
    "id": "vocab-205",
    "word": "recycle",
    "ipa": "/ˌriːˈsaɪ.kəl/",
    "meaning": "tái chế",
    "category": "environment",
    "level": "basic",
    "image": "♻️",
    "sentence": "Recycle paper and plastic bottles.",
    "sentenceVi": "Tái chế giấy và chai nhựa.",
    "hint": "Từ vựng từ điển chuẩn (environment): tái chế"
  },
  {
    "id": "vocab-206",
    "word": "clean",
    "ipa": "/kliːn/",
    "meaning": "sạch sẻ",
    "category": "environment",
    "level": "basic",
    "image": "✨",
    "sentence": "Keep your surrounding environment clean.",
    "sentenceVi": "Giữ môi trường sống xung quanh luôn sạch sẽ.",
    "hint": "Từ vựng từ điển chuẩn (environment): sạch sẻ"
  },
  {
    "id": "vocab-207",
    "word": "earth",
    "ipa": "/ɜːθ/",
    "meaning": "Trái Đất",
    "category": "environment",
    "level": "elementary",
    "image": "🌍",
    "sentence": "Protect our green planet Earth.",
    "sentenceVi": "Bảo vệ Trái Đất hành tinh xanh của chúng ta.",
    "hint": "Từ vựng từ điển chuẩn (environment): Trái Đất"
  },
  {
    "id": "vocab-208",
    "word": "planet",
    "ipa": "/ˈplæn.ɪt/",
    "meaning": "hành tinh",
    "category": "science",
    "level": "elementary",
    "image": "🪐",
    "sentence": "Saturn is a beautiful ringed planet.",
    "sentenceVi": "Sao Thổ là một hành tinh có vành đai tuyệt đẹp.",
    "hint": "Từ vựng từ điển chuẩn (science): hành tinh"
  },
  {
    "id": "vocab-209",
    "word": "astronaut",
    "ipa": "/ˈæs.trə.nɔːt/",
    "meaning": "phi hành gia",
    "category": "science",
    "level": "intermediate",
    "image": "👨‍🚀",
    "sentence": "Astronauts travel into outer space.",
    "sentenceVi": "Các phi hành gia bay vào vũ trụ bao la.",
    "hint": "Từ vựng từ điển chuẩn (science): phi hành gia"
  },
  {
    "id": "vocab-210",
    "word": "discipline",
    "ipa": "/ˈdɪs.ə.plɪn/",
    "meaning": "kỷ luật bản thân",
    "category": "lifeskills",
    "level": "intermediate",
    "image": "🎯",
    "sentence": "Self-discipline leads to success.",
    "sentenceVi": "Kỷ luật bản thân dẫn lối tới thành công.",
    "hint": "Từ vựng từ điển chuẩn (lifeskills): kỷ luật bản thân"
  },
  {
    "id": "vocab-211",
    "word": "creativity",
    "ipa": "/ˌkriː.eɪˈtɪv.ə.ti/",
    "meaning": "sự sáng tạo",
    "category": "lifeskills",
    "level": "intermediate",
    "image": "💡",
    "sentence": "Unleash your unlimited creativity.",
    "sentenceVi": "Khơi dậy khả năng sáng tạo không giới hạn.",
    "hint": "Từ vựng từ điển chuẩn (lifeskills): sự sáng tạo"
  },
  {
    "id": "vocab-212",
    "word": "empathy",
    "ipa": "/ˈem.pə.θi/",
    "meaning": "sự thấu cảm",
    "category": "lifeskills",
    "level": "intermediate",
    "image": "❤️",
    "sentence": "Empathy helps understand others.",
    "sentenceVi": "Sự thấu cảm giúp chúng ta thấu hiểu người khác.",
    "hint": "Từ vựng từ điển chuẩn (lifeskills): sự thấu cảm"
  }
];
