/**
 * CHRONOFLOW ENTERPRISE v2.0 - MATERNAL & POSTPARTUM SCHEDULE PLATFORM
 * Dữ liệu nghiệp vụ & kỹ thuật chuẩn y tế cho Phụ Nữ Mang Thai & Sau Sinh
 * Tuân thủ hướng dẫn WHO, CDC, ACOG & Quy chuẩn Bộ Y tế Việt Nam.
 */

export const MATERNAL_SAFETY_DISCLAIMER =
  'Tuyên bố an toàn: Hệ thống hỗ trợ tổ chức lịch và nhắc việc, không chẩn đoán, không thay thế bác sĩ hoặc cơ sở y tế. Nội dung có tính lâm sàng phải được đơn vị triển khai và người có chuyên môn phê duyệt.';

// CDC & WHO Urgent Maternal Warning Signs (Danh mục cảnh báo khẩn cấp)
export const URGENT_WARNING_SIGNS = [
  {
    id: 'warn-1',
    title: 'Khó thở hoặc đau ngực',
    audience: 'both', // 'pregnant' | 'postpartum' | 'both'
    severity: 'EMERGENCY',
    action: 'Tìm chăm sóc y tế khẩn cấp ngay. Gọi 115 hoặc đến bệnh viện nearest.',
    source: 'CDC Hear Her Campaign / WHO Maternal Care Guidelines',
    active: true,
  },
  {
    id: 'warn-2',
    title: 'Ngất, co giật hoặc lú lẫn',
    audience: 'both',
    severity: 'EMERGENCY',
    action: 'Gọi cấp cứu 115 hoặc nhờ người thân đưa đến phòng cấp cứu ngay lập tức.',
    source: 'CDC Urgent Maternal Warning Signs',
    active: true,
  },
  {
    id: 'warn-3',
    title: 'Sốt cao từ 38°C trở lên',
    audience: 'both',
    severity: 'HIGH',
    action: 'Liên hệ cơ sở y tế ngay để được bác sĩ đánh giá nguy cơ nhiễm trùng.',
    source: 'WHO Postnatal Care Guidelines',
    active: true,
  },
  {
    id: 'warn-4',
    title: 'Đau đầu dữ dội / Thay đổi thị lực (nhìn mờ, hoa mắt)',
    audience: 'both',
    severity: 'HIGH',
    action: 'Đến cơ sở y tế ngay để kiểm tra huyết áp (Nguy cơ Tiền sản giật / Tăng huyết áp thai kỳ).',
    source: 'ACOG Clinical Guidance on Preeclampsia',
    active: true,
  },
  {
    id: 'warn-5',
    title: 'Ra máu âm đạo hoặc rỉ dịch thai kỳ',
    audience: 'pregnant',
    severity: 'EMERGENCY',
    action: 'Đến ngay bệnh viện phụ sản gần nhất để kiểm tra tim thai và cổ tử cung.',
    source: 'Bộ Y tế - Hướng dẫn quốc gia về dịch vụ chăm sóc sức khỏe sinh sản',
    active: true,
  },
  {
    id: 'warn-6',
    title: 'Chảy máu âm đạo nhiều hoặc sản dịch có mùi hôi hôi bất thường',
    audience: 'postpartum',
    severity: 'EMERGENCY',
    action: 'Tìm chăm sóc y tế ngay (Nguy cơ Băng huyết sau sinh hoặc Nhiễm trùng hậu phẫu).',
    source: 'WHO Postpartum Hemorrhage & Infection Prevention',
    active: true,
  },
  {
    id: 'warn-7',
    title: 'Sưng, đỏ, nóng hoặc đau ở một bên chân (đùi/bắp chân)',
    audience: 'both',
    severity: 'HIGH',
    action: 'Đến cơ sở y tế ngay để siêu âm mạch máu (Nguy cơ Huyết khối tĩnh mạch sâu DVT).',
    source: 'CDC Urgent Warning Signs',
    active: true,
  },
  {
    id: 'warn-8',
    title: 'Cảm giác lo âu tột độ, kiệt sức hoặc suy nghĩ làm hại bản thân / em bé',
    audience: 'postpartum',
    severity: 'EMERGENCY',
    action: 'Không ở một mình! Hãy chia sẻ ngay với người thân và liên hệ hotline tâm thần/bác sĩ tâm lý cấp cứu.',
    source: 'ACOG Postpartum Mental Health Screening',
    active: true,
  },
];

// Maternal Reminder Templates (Danh mục mẫu nhắc việc theo giai đoạn)
export const MATERNAL_REMINDER_TEMPLATES = [
  // PREGNANCY REMINDERS
  {
    id: 'rem-preg-1',
    audience: 'pregnant',
    category: 'Khám thai',
    title: 'Nhắc lịch khám thai định kỳ',
    message: 'Chuẩn bị hồ sơ khám cũ, danh sách câu hỏi và đến cơ sở y tế theo lịch hẹn.',
    stageRange: 'Tuần 1 - Tuần 40',
    recurrence: 'Theo chỉ định Bác sĩ (Tối thiểu 8 lần tiếp xúc WHO)',
    time: '08:00',
    priority: 'HIGH',
    channels: ['in_app', 'push'],
    clinicianApprovalRequired: true,
    approvalStatus: 'APPROVED',
    source: 'WHO Antenatal Care Recommendations',
  },
  {
    id: 'rem-preg-2',
    audience: 'pregnant',
    category: 'Thuốc & Vi chất',
    title: 'Dùng Axit Folic, Sắt & Canxi theo đơn',
    message: 'Uống đúng liều lượng chỉ định của Bác sĩ. Không tự ý ngưng hoặc thêm thuốc.',
    stageRange: 'Suốt thai kỳ',
    recurrence: 'Hàng ngày',
    time: '07:00',
    priority: 'HIGH',
    channels: ['in_app', 'sms'],
    clinicianApprovalRequired: true,
    approvalStatus: 'APPROVED',
    source: 'Bộ Y tế - Hướng dẫn Bổ sung Vi chất Thai kỳ',
  },
  {
    id: 'rem-preg-3',
    audience: 'pregnant',
    category: 'Thai máy',
    title: 'Theo dõi chỉ số thai máy (Kick Count)',
    message: 'Nằm nghỉ tĩnh lặng, đếm số lần cử động thai trong 1 tiếng sau bữa ăn (Cần có 4+ lần cử động).',
    stageRange: 'Tuần 28 - Tuần 40',
    recurrence: '2 lần / ngày',
    time: '13:00',
    priority: 'HIGH',
    channels: ['in_app'],
    clinicianApprovalRequired: true,
    approvalStatus: 'APPROVED',
    source: 'ACOG Fetal Movement Counting Guidelines',
  },
  {
    id: 'rem-preg-4',
    audience: 'pregnant',
    category: 'Xét nghiệm & Siêu âm',
    title: 'Siêu âm hình thái thai nhi (Khung giờ vàng 20-22 tuần)',
    message: 'Kiểm tra cấu trúc cơ quan nội tạng thai nhi tại cơ sở y tế có chuyên môn.',
    stageRange: 'Tuần 20 - Tuần 22',
    recurrence: 'Một lần',
    time: '09:00',
    priority: 'HIGH',
    channels: ['in_app', 'push'],
    clinicianApprovalRequired: true,
    approvalStatus: 'APPROVED',
    source: 'Bộ Y tế - Sàng lọc Trước sinh',
  },

  // POSTPARTUM REMINDERS
  {
    id: 'rem-post-1',
    audience: 'postpartum',
    category: 'Tái khám sau sinh',
    title: 'Nhắc lịch tái khám sau sinh 6 tuần',
    message: 'Khám kiểm tra sự hồi phục tử cung, tầng sinh môn/vết mổ và sức khỏe tinh thần.',
    stageRange: 'Ngày 42 sau sinh (Tuần 6)',
    recurrence: 'Một lần',
    time: '08:30',
    priority: 'HIGH',
    channels: ['in_app', 'push'],
    clinicianApprovalRequired: true,
    approvalStatus: 'APPROVED',
    source: 'ACOG Optimizing Postpartum Care',
  },
  {
    id: 'rem-post-2',
    audience: 'postpartum',
    category: 'Sản dịch & Vết mổ',
    title: 'Kiểm tra sản dịch và vệ sinh vết khâu/vết mổ',
    message: 'Vệ sinh khô ráo, quan sát màu sắc & mùi sản dịch. Báo bác sĩ ngay nếu sản dịch hôi hoặc ra máu cục to.',
    stageRange: 'Ngày 1 - Ngày 30 sau sinh',
    recurrence: 'Hàng ngày',
    time: '07:30',
    priority: 'HIGH',
    channels: ['in_app'],
    clinicianApprovalRequired: true,
    approvalStatus: 'APPROVED',
    source: 'WHO Postnatal Care for Mothers',
  },
  {
    id: 'rem-post-3',
    audience: 'postpartum',
    category: 'Nuôi dưỡng trẻ',
    title: 'Cho con bú mẹ / Vắt sữa & theo dõi cữ bé',
    message: 'Cho bé bú đúng tư thế, vắt sữa đều đặn 2.5h-3h/lần để tránh tắc tia sữa & viêm tuyến vú.',
    stageRange: '6 tháng đầu sau sinh',
    recurrence: 'Theo cữ bú của trẻ (3-4 tiếng/lần)',
    time: '09:00',
    priority: 'MEDIUM',
    channels: ['in_app'],
    clinicianApprovalRequired: false,
    approvalStatus: 'APPROVED',
    source: 'WHO Infant & Young Child Feeding',
  },
  {
    id: 'rem-post-4',
    audience: 'postpartum',
    category: 'Tinh thần & Check-in',
    title: 'Check-in cảm xúc & Sàng lọc sức khỏe tâm thần',
    message: 'Dành 2 phút ghi nhận mức độ mệt mỏi, lo âu. Chia sẻ ngay với người thân nếu thấy quá tải.',
    stageRange: 'Tuần 1 - Tuần 12 sau sinh',
    recurrence: 'Hàng ngày',
    time: '20:00',
    priority: 'HIGH',
    channels: ['in_app'],
    clinicianApprovalRequired: true,
    approvalStatus: 'APPROVED',
    source: 'Edinburgh Postnatal Depression Scale (EPDS) / ACOG',
  },
];

// Content Review Workflow States (Quy trình duyệt 5 bước AD-07)
export const CONTENT_APPROVAL_WORKFLOW = [
  { status: 'DRAFT', label: 'Bản nháp (Draft)', color: 'bg-slate-700 text-slate-300' },
  { status: 'PENDING_REVIEW', label: 'Chờ duyệt chuyên môn', color: 'bg-amber-900/60 text-amber-300 border-amber-500/40' },
  { status: 'APPROVED', label: 'Đã duyệt chuyên môn', color: 'bg-emerald-900/60 text-emerald-300 border-emerald-500/40' },
  { status: 'PUBLISHED', label: 'Đang phát hành', color: 'bg-sky-900/60 text-sky-300 border-sky-500/40' },
  { status: 'RETIRED', label: 'Ngừng sử dụng', color: 'bg-rose-900/60 text-rose-300 border-rose-500/40' },
];

// Granular Role & Permission Definitions (Section 2 & AD-09)
export const MATERNAL_ROLES = {
  admin: {
    id: 'admin',
    name: 'Quản trị viên (System Admin)',
    badge: 'ADMIN MASTER',
    color: 'bg-purple-500/20 text-purple-300 border-purple-500/40',
    description: 'Vận hành toàn bộ nền tảng, quản lý người dùng, hồ sơ, mẫu nhắc, duyệt nội dung & xuất báo cáo Audit.',
    permissions: ['all', 'manage_users', 'edit_schedules', 'manage_reminders', 'approve_clinical', 'export_word', 'audit_logs'],
  },
  clinician: {
    id: 'clinician',
    name: 'Người duyệt chuyên môn (Clinical Reviewer)',
    badge: 'CLINICAL REVIEWER 🩺',
    color: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
    description: 'Rà soát & phê duyệt các nội dung y khoa/lâm sàng, gán kế hoạch chăm sóc theo hồ sơ y tế.',
    permissions: ['read', 'approve_clinical', 'edit_schedules', 'manage_reminders', 'export_word'],
  },
  pregnant: {
    id: 'pregnant',
    name: 'Phụ nữ mang thai (Pregnancy Phase)',
    badge: 'PREGNANCY 🤰',
    color: 'bg-pink-500/20 text-pink-300 border-pink-500/40',
    description: 'Theo dõi lịch sinh hoạt thai kỳ 7 ngày, check-in triệu chứng, đếm thai máy & xem cảnh báo an toàn CDC/WHO.',
    permissions: ['read', 'check_in', 'edit_unlocked_cells', 'export_word'],
  },
  postpartum: {
    id: 'postpartum',
    name: 'Phụ nữ sau sinh (Postpartum Phase)',
    badge: 'POSTPARTUM 🤱',
    color: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
    description: 'Theo dõi hồi phục sau sinh, lịch tái khám, cữ bú của trẻ, check-in tâm trạng & xem cảnh báo nguy hiểm.',
    permissions: ['read', 'check_in', 'edit_unlocked_cells', 'export_word'],
  },
};
